const String baseUrl = 'https://lkyhub.xyz/';
const String memberBaseUrl = 'https://lkyhub.xyz/Member/';
const String validateUserName = '${memberBaseUrl}validateUsername';

const String dummyAuthToken =
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjcxOTYwNzksImlzcyI6IiIsImV4cCI6MTY2NzI4MjQ3OSwidXNlclRva2VuIjoiOElIOEJlaXRHT0lqampyajdPV2pZVGhueG0xTWlSZG11aldPVEowdHdpOENxYWh4NWkzOTBLakFLaXc4Nkx2SmtmbzNsMlh1ZVdVR2ppY0IzWHc2TFFJcFY0QW5xOXE2VUlHTnpMZnNTWEI1NTI2cXEyeVNiOTNLMDJQMElydjFxRzhscFpnY2N1UWlxWmQ3a1FWRmNNNThXbzFoWFV4SXg4SmxkOHdrUkRZVWtJWFBHN2RNcXhYckR6WU9PendCamM2MTNmelgiLCJ1c2VyVHlwZSI6Im1lbWJlciIsInVzZXJBdXRoIjoiaTlld3ZUbnhqTkh5VTNpZkdMQWdLN3R1ekxJeGdaZVRYNzI1eGdhTlNmWEwxWnMzTFR2SXpqMXRzWTZEbG1EVkJlbFM2VWJPdFpnRkFCeGMwNDBkV1MwMDViU29JUWVaS3BpbTRyOGFzdHhodW5mM1AxT3N5VHBiVXhxZVFoa2xOd1I1OEtzU043d3NwN0xsdEFaR1RLSmptYXAxaHlZSHN6SUJGc2dwTnkxcWhFMnpQUmY4S1VLSWNpb3U5dlRyZ1RjcXBqTDkifQ.q5b5_2jwOBR5a1Gax4_3MwmgxH9FE2EQD-8z-gk9IU8';
