///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GamePlayModelResponseGameDetails {
/*
{
  "Url": "https://ttt.onlinegames22.com/player/login/apiLogin0?userId=gMi16n3c00085&agentId=lky&tokenId=do3xx5qxJ9_KI3TrMqDmAiSg0L6ZG_f_B6OAoNFEaV65Zi4OXMbhag&isMobileLogin=1&isShowSymbol=true&currencySymbol=&isApp=false&platform=PP&gameType=&gameForbidden=%7B%22AWS%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22TABLE%22%3A%5B%22ALL%22%5D%2C%22EGAME%22%3A%5B%22ALL%22%5D%7D%2C%22JDBFISH%22%3A%7B%22FH%22%3A%5B%22ALL%22%5D%7D%2C%22JILI%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22FH%22%3A%5B%22ALL%22%5D%2C%22TABLE%22%3A%5B%22ALL%22%5D%7D%2C%22KINGMAKER%22%3A%7B%22TABLE%22%3A%5B%22ALL%22%5D%7D%2C%22PG%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22TABLE%22%3A%5B%22ALL%22%5D%7D%2C%22RT%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22TABLE%22%3A%5B%22ALL%22%5D%7D%2C%22SEXYBCRT%22%3A%7B%22LIVE%22%3A%5B%22ALL%22%5D%7D%2C%22SV388%22%3A%7B%22LIVE%22%3A%5B%22ALL%22%5D%7D%2C%22SPADE%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22FH%22%3A%5B%22ALL%22%5D%2C%22EGAME%22%3A%5B%22ALL%22%5D%7D%2C%22YL%22%3A%7B%22FH%22%3A%5B%22ALL%22%5D%7D%7D&language=en&hall=SEXY"
} 
*/

  String? Url;

  GamePlayModelResponseGameDetails({
    this.Url,
  });
  GamePlayModelResponseGameDetails.fromJson(Map<String, dynamic> json) {
    Url = json['Url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Url'] = Url;
    return data;
  }
}

class GamePlayModelResponse {
/*
{
  "gameDetails": {
    "Url": "https://ttt.onlinegames22.com/player/login/apiLogin0?userId=gMi16n3c00085&agentId=lky&tokenId=do3xx5qxJ9_KI3TrMqDmAiSg0L6ZG_f_B6OAoNFEaV65Zi4OXMbhag&isMobileLogin=1&isShowSymbol=true&currencySymbol=&isApp=false&platform=PP&gameType=&gameForbidden=%7B%22AWS%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22TABLE%22%3A%5B%22ALL%22%5D%2C%22EGAME%22%3A%5B%22ALL%22%5D%7D%2C%22JDBFISH%22%3A%7B%22FH%22%3A%5B%22ALL%22%5D%7D%2C%22JILI%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22FH%22%3A%5B%22ALL%22%5D%2C%22TABLE%22%3A%5B%22ALL%22%5D%7D%2C%22KINGMAKER%22%3A%7B%22TABLE%22%3A%5B%22ALL%22%5D%7D%2C%22PG%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22TABLE%22%3A%5B%22ALL%22%5D%7D%2C%22RT%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22TABLE%22%3A%5B%22ALL%22%5D%7D%2C%22SEXYBCRT%22%3A%7B%22LIVE%22%3A%5B%22ALL%22%5D%7D%2C%22SV388%22%3A%7B%22LIVE%22%3A%5B%22ALL%22%5D%7D%2C%22SPADE%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22FH%22%3A%5B%22ALL%22%5D%2C%22EGAME%22%3A%5B%22ALL%22%5D%7D%2C%22YL%22%3A%7B%22FH%22%3A%5B%22ALL%22%5D%7D%7D&language=en&hall=SEXY"
  }
} 
*/

  GamePlayModelResponseGameDetails? gameDetails;

  GamePlayModelResponse({
    this.gameDetails,
  });
  GamePlayModelResponse.fromJson(Map<String, dynamic> json) {
    gameDetails = (json['gameDetails'] != null)
        ? GamePlayModelResponseGameDetails.fromJson(json['gameDetails'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (gameDetails != null) {
      data['gameDetails'] = gameDetails!.toJson();
    }
    return data;
  }
}

class GamePlayModel {
/*
{
  "msg": "[SEXY] Get Game Launch Details Success.",
  "response": {
    "gameDetails": {
      "Url": "https://ttt.onlinegames22.com/player/login/apiLogin0?userId=gMi16n3c00085&agentId=lky&tokenId=do3xx5qxJ9_KI3TrMqDmAiSg0L6ZG_f_B6OAoNFEaV65Zi4OXMbhag&isMobileLogin=1&isShowSymbol=true&currencySymbol=&isApp=false&platform=PP&gameType=&gameForbidden=%7B%22AWS%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22TABLE%22%3A%5B%22ALL%22%5D%2C%22EGAME%22%3A%5B%22ALL%22%5D%7D%2C%22JDBFISH%22%3A%7B%22FH%22%3A%5B%22ALL%22%5D%7D%2C%22JILI%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22FH%22%3A%5B%22ALL%22%5D%2C%22TABLE%22%3A%5B%22ALL%22%5D%7D%2C%22KINGMAKER%22%3A%7B%22TABLE%22%3A%5B%22ALL%22%5D%7D%2C%22PG%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22TABLE%22%3A%5B%22ALL%22%5D%7D%2C%22RT%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22TABLE%22%3A%5B%22ALL%22%5D%7D%2C%22SEXYBCRT%22%3A%7B%22LIVE%22%3A%5B%22ALL%22%5D%7D%2C%22SV388%22%3A%7B%22LIVE%22%3A%5B%22ALL%22%5D%7D%2C%22SPADE%22%3A%7B%22SLOT%22%3A%5B%22ALL%22%5D%2C%22FH%22%3A%5B%22ALL%22%5D%2C%22EGAME%22%3A%5B%22ALL%22%5D%7D%2C%22YL%22%3A%7B%22FH%22%3A%5B%22ALL%22%5D%7D%7D&language=en&hall=SEXY"
    }
  }
} 
*/

  String? msg;
  GamePlayModelResponse? response;

  GamePlayModel({
    this.msg,
    this.response,
  });
  GamePlayModel.fromJson(Map<String, dynamic> json) {
    msg = json['msg']?.toString();
    response = (json['response'] != null)
        ? GamePlayModelResponse.fromJson(json['response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['msg'] = msg;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
