///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PendtingTopUpModelResponseInfo {
/*
{
  "topup_id": "44794",
  "wallet_id": "25663",
  "topup_amount": "50.00",
  "topup_amount_previous": "11434.08",
  "topup_amount_balance": "11484.08",
  "topup_datetime": "2022-12-07 00:15:05",
  "update_datetime": null,
  "topup_status": "pending",
  "promo_id": null,
  "topup_receipt_url": "1",
  "topup_remarks": null,
  "topup_bank_id": "24",
  "topup_number": "DIRECT221207121505832785",
  "topup_type": "bank",
  "done_by_admin_id": null,
  "done_by_admin_name": null,
  "topup_direct_param": null,
  "topup_direct_response": null,
  "topup_unique_key": null,
  "topup_original_amount": null,
  "topup_conversion_rate": null,
  "topup_service_charge": null,
  "topup_owner_name": null,
  "topup_method": null,
  "topup_receipt": null,
  "member_id": "21",
  "wallet_balance": "11434.08",
  "wallet_created_datetime": "2022-05-23 17:39:23",
  "wallet_update_datetime": "2022-11-30 14:13:06",
  "wallet_pin": "000000",
  "wallet_pin_reset_otp": null,
  "wallet_country": "2",
  "wallet_topup_bank_id": null,
  "wallet_topup_bank_amount": null,
  "id": "21",
  "member_unique_key": "CvrKJgMi16n3crLQ7CRprRKYihf9epbnp29DOcd3tW4FMyNpHYUQX6V7DERpzUY4DDcz8O9pOaR4PxogOGkysdPSNPxJB2gpABtfTkloRsMKxfY8Txklj0OCtHnOUKV0kaBmNBaZNsW3eOtUNelSM3rQ6zOLoxcsgAAaqRskdqygk5lIBRrsVbuBRcHpMIMTAD8aUeNW",
  "password": "68ea8013e0b1da0f9e01f6831a5fcf9a",
  "salt": "5sUTZHtm3AAlX/c4WL5DJzU6IG0kKnFENiWTicLKV3tcLG.5EOj9WQ==",
  "member_username": "Techtest",
  "member_level": "2",
  "ref_upline": "2",
  "member_main_id": "2",
  "member_phone_country": "+60",
  "member_phone": "103600016",
  "member_phone_otp": null,
  "member_phone_otp_salt": null,
  "member_phone_otp_status": "true",
  "last_login": "2022-12-07 13:39:28",
  "user_email": null,
  "registration_token": null,
  "account_status": "active",
  "account_status_remarks": null,
  "created_datetime": "2021-04-30 19:56:17",
  "password_otp": null,
  "password_otp_salt": null,
  "password_expiry": "2022-01-21 02:30:29",
  "bank_account_number": "123456789",
  "bank_id": "2",
  "shareholder_unique_key": "aHxbKIEsjLXK6jfsr3KNEuxFMuZkTpy9BMNzxyKOLwbVUuDV7DJLX7W9IY2eI6C1Abpw5YJPXiftI4I0DIj7MBUsTdtnKHVjEqdoRDtkSpEik4XdF1ZB1bapwMZINSmzaMH3EFAbUQuxWyto7sXPhp8IKcSpUE80kY2mYMnuuk1bjPnM5ovUfM6y0Ay3YozzDxRXNANJ",
  "bank_account_name": "Ggggg",
  "pin_status": "true",
  "member_nickname": "techtest11",
  "last_login_ip": "172.70.142.184",
  "member_avatar_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/avatar/10.jpg",
  "member_qrcode_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/consumer/avatar/1675683361.png",
  "auth_session": "9TRlMTMYUzZVcdooY0K3gdIlweQxpPIi22n9XG1epfYzJHRhlOAudCY3yM29MeCzOrfycCreUGv19LwfCThIJUfDEQHDLStjkkK0iJTuF2X5BQAWl5dIEzJ92boXuLTrjDiwfp5A26xM10eRpmomHCYMQaOtJrLiYCJYXJBw2aHfZ0tcsGwp5XEyAJqZcrIJ8abfdaXu",
  "auth_expiry": "2022-12-08 13:39:28",
  "member_type": "normal",
  "admin_override": "false",
  "admin_override_expiry_datetime": null,
  "member_device_id": "58c549bc790a5ed4",
  "member_device": "Windows",
  "trace_history": "21-",
  "shareholder_trace_history": "1-",
  "json_trace_history": "[\"21\", \"\"]",
  "member_qrcode_url_new": null,
  "avatar_last_update": "2021-06-16 22:48:09",
  "json_shareholder_trace_history": "[\"1\", \"\"]",
  "fcm_token": "",
  "member_language": "en",
  "member_permission": null,
  "member_referral_url": null,
  "member_directline": "0",
  "member_login_token": null,
  "member_country": "2",
  "vip_level_id": null,
  "member_country_origin": "1",
  "is_transferring": "0",
  "member_topup_bank_id": null,
  "vip_last_update": null,
  "first_time_login": "false",
  "topupBankName": "CK Wah Global Trading",
  "topupBankNo": "514383615084",
  "topupBank": "Maybank",
  "countdown": 0
} 
*/

  String? topupId;
  String? walletId;
  String? topupAmount;
  String? topupAmountPrevious;
  String? topupAmountBalance;
  String? topupDatetime;
  String? updateDatetime;
  String? topupStatus;
  String? promoId;
  String? topupReceiptUrl;
  String? topupRemarks;
  String? topupBankId;
  String? topupNumber;
  String? topupType;
  String? doneByAdminId;
  String? doneByAdminName;
  String? topupDirectParam;
  String? topupDirectResponse;
  String? topupUniqueKey;
  String? topupOriginalAmount;
  String? topupConversionRate;
  String? topupServiceCharge;
  String? topupOwnerName;
  String? topupMethod;
  String? topupReceipt;
  String? memberId;
  String? walletBalance;
  String? walletCreatedDatetime;
  String? walletUpdateDatetime;
  String? walletPin;
  String? walletPinResetOtp;
  String? walletCountry;
  String? walletTopupBankId;
  String? walletTopupBankAmount;
  String? id;
  String? memberUniqueKey;
  String? password;
  String? salt;
  String? memberUsername;
  String? memberLevel;
  String? refUpline;
  String? memberMainId;
  String? memberPhoneCountry;
  String? memberPhone;
  String? memberPhoneOtp;
  String? memberPhoneOtpSalt;
  String? memberPhoneOtpStatus;
  String? lastLogin;
  String? userEmail;
  String? registrationToken;
  String? accountStatus;
  String? accountStatusRemarks;
  String? createdDatetime;
  String? passwordOtp;
  String? passwordOtpSalt;
  String? passwordExpiry;
  String? bankAccountNumber;
  String? bankId;
  String? shareholderUniqueKey;
  String? bankAccountName;
  String? pinStatus;
  String? memberNickname;
  String? lastLoginIp;
  String? memberAvatarUrl;
  String? memberQrcodeUrl;
  String? authSession;
  String? authExpiry;
  String? memberType;
  String? adminOverride;
  String? adminOverrideExpiryDatetime;
  String? memberDeviceId;
  String? memberDevice;
  String? traceHistory;
  String? shareholderTraceHistory;
  String? jsonTraceHistory;
  String? memberQrcodeUrlNew;
  String? avatarLastUpdate;
  String? jsonShareholderTraceHistory;
  String? fcmToken;
  String? memberLanguage;
  String? memberPermission;
  String? memberReferralUrl;
  String? memberDirectline;
  String? memberLoginToken;
  String? memberCountry;
  String? vipLevelId;
  String? memberCountryOrigin;
  String? isTransferring;
  String? memberTopupBankId;
  String? vipLastUpdate;
  String? firstTimeLogin;
  String? topupBankName;
  String? topupBankNo;
  String? topupBank;
  int? countdown;

  PendtingTopUpModelResponseInfo({
    this.topupId,
    this.walletId,
    this.topupAmount,
    this.topupAmountPrevious,
    this.topupAmountBalance,
    this.topupDatetime,
    this.updateDatetime,
    this.topupStatus,
    this.promoId,
    this.topupReceiptUrl,
    this.topupRemarks,
    this.topupBankId,
    this.topupNumber,
    this.topupType,
    this.doneByAdminId,
    this.doneByAdminName,
    this.topupDirectParam,
    this.topupDirectResponse,
    this.topupUniqueKey,
    this.topupOriginalAmount,
    this.topupConversionRate,
    this.topupServiceCharge,
    this.topupOwnerName,
    this.topupMethod,
    this.topupReceipt,
    this.memberId,
    this.walletBalance,
    this.walletCreatedDatetime,
    this.walletUpdateDatetime,
    this.walletPin,
    this.walletPinResetOtp,
    this.walletCountry,
    this.walletTopupBankId,
    this.walletTopupBankAmount,
    this.id,
    this.memberUniqueKey,
    this.password,
    this.salt,
    this.memberUsername,
    this.memberLevel,
    this.refUpline,
    this.memberMainId,
    this.memberPhoneCountry,
    this.memberPhone,
    this.memberPhoneOtp,
    this.memberPhoneOtpSalt,
    this.memberPhoneOtpStatus,
    this.lastLogin,
    this.userEmail,
    this.registrationToken,
    this.accountStatus,
    this.accountStatusRemarks,
    this.createdDatetime,
    this.passwordOtp,
    this.passwordOtpSalt,
    this.passwordExpiry,
    this.bankAccountNumber,
    this.bankId,
    this.shareholderUniqueKey,
    this.bankAccountName,
    this.pinStatus,
    this.memberNickname,
    this.lastLoginIp,
    this.memberAvatarUrl,
    this.memberQrcodeUrl,
    this.authSession,
    this.authExpiry,
    this.memberType,
    this.adminOverride,
    this.adminOverrideExpiryDatetime,
    this.memberDeviceId,
    this.memberDevice,
    this.traceHistory,
    this.shareholderTraceHistory,
    this.jsonTraceHistory,
    this.memberQrcodeUrlNew,
    this.avatarLastUpdate,
    this.jsonShareholderTraceHistory,
    this.fcmToken,
    this.memberLanguage,
    this.memberPermission,
    this.memberReferralUrl,
    this.memberDirectline,
    this.memberLoginToken,
    this.memberCountry,
    this.vipLevelId,
    this.memberCountryOrigin,
    this.isTransferring,
    this.memberTopupBankId,
    this.vipLastUpdate,
    this.firstTimeLogin,
    this.topupBankName,
    this.topupBankNo,
    this.topupBank,
    this.countdown,
  });
  PendtingTopUpModelResponseInfo.fromJson(Map<String, dynamic> json) {
    topupId = json['topup_id']?.toString();
    walletId = json['wallet_id']?.toString();
    topupAmount = json['topup_amount']?.toString();
    topupAmountPrevious = json['topup_amount_previous']?.toString();
    topupAmountBalance = json['topup_amount_balance']?.toString();
    topupDatetime = json['topup_datetime']?.toString();
    updateDatetime = json['update_datetime']?.toString();
    topupStatus = json['topup_status']?.toString();
    promoId = json['promo_id']?.toString();
    topupReceiptUrl = json['topup_receipt_url']?.toString();
    topupRemarks = json['topup_remarks']?.toString();
    topupBankId = json['topup_bank_id']?.toString();
    topupNumber = json['topup_number']?.toString();
    topupType = json['topup_type']?.toString();
    doneByAdminId = json['done_by_admin_id']?.toString();
    doneByAdminName = json['done_by_admin_name']?.toString();
    topupDirectParam = json['topup_direct_param']?.toString();
    topupDirectResponse = json['topup_direct_response']?.toString();
    topupUniqueKey = json['topup_unique_key']?.toString();
    topupOriginalAmount = json['topup_original_amount']?.toString();
    topupConversionRate = json['topup_conversion_rate']?.toString();
    topupServiceCharge = json['topup_service_charge']?.toString();
    topupOwnerName = json['topup_owner_name']?.toString();
    topupMethod = json['topup_method']?.toString();
    topupReceipt = json['topup_receipt']?.toString();
    memberId = json['member_id']?.toString();
    walletBalance = json['wallet_balance']?.toString();
    walletCreatedDatetime = json['wallet_created_datetime']?.toString();
    walletUpdateDatetime = json['wallet_update_datetime']?.toString();
    walletPin = json['wallet_pin']?.toString();
    walletPinResetOtp = json['wallet_pin_reset_otp']?.toString();
    walletCountry = json['wallet_country']?.toString();
    walletTopupBankId = json['wallet_topup_bank_id']?.toString();
    walletTopupBankAmount = json['wallet_topup_bank_amount']?.toString();
    id = json['id']?.toString();
    memberUniqueKey = json['member_unique_key']?.toString();
    password = json['password']?.toString();
    salt = json['salt']?.toString();
    memberUsername = json['member_username']?.toString();
    memberLevel = json['member_level']?.toString();
    refUpline = json['ref_upline']?.toString();
    memberMainId = json['member_main_id']?.toString();
    memberPhoneCountry = json['member_phone_country']?.toString();
    memberPhone = json['member_phone']?.toString();
    memberPhoneOtp = json['member_phone_otp']?.toString();
    memberPhoneOtpSalt = json['member_phone_otp_salt']?.toString();
    memberPhoneOtpStatus = json['member_phone_otp_status']?.toString();
    lastLogin = json['last_login']?.toString();
    userEmail = json['user_email']?.toString();
    registrationToken = json['registration_token']?.toString();
    accountStatus = json['account_status']?.toString();
    accountStatusRemarks = json['account_status_remarks']?.toString();
    createdDatetime = json['created_datetime']?.toString();
    passwordOtp = json['password_otp']?.toString();
    passwordOtpSalt = json['password_otp_salt']?.toString();
    passwordExpiry = json['password_expiry']?.toString();
    bankAccountNumber = json['bank_account_number']?.toString();
    bankId = json['bank_id']?.toString();
    shareholderUniqueKey = json['shareholder_unique_key']?.toString();
    bankAccountName = json['bank_account_name']?.toString();
    pinStatus = json['pin_status']?.toString();
    memberNickname = json['member_nickname']?.toString();
    lastLoginIp = json['last_login_ip']?.toString();
    memberAvatarUrl = json['member_avatar_url']?.toString();
    memberQrcodeUrl = json['member_qrcode_url']?.toString();
    authSession = json['auth_session']?.toString();
    authExpiry = json['auth_expiry']?.toString();
    memberType = json['member_type']?.toString();
    adminOverride = json['admin_override']?.toString();
    adminOverrideExpiryDatetime =
        json['admin_override_expiry_datetime']?.toString();
    memberDeviceId = json['member_device_id']?.toString();
    memberDevice = json['member_device']?.toString();
    traceHistory = json['trace_history']?.toString();
    shareholderTraceHistory = json['shareholder_trace_history']?.toString();
    jsonTraceHistory = json['json_trace_history']?.toString();
    memberQrcodeUrlNew = json['member_qrcode_url_new']?.toString();
    avatarLastUpdate = json['avatar_last_update']?.toString();
    jsonShareholderTraceHistory =
        json['json_shareholder_trace_history']?.toString();
    fcmToken = json['fcm_token']?.toString();
    memberLanguage = json['member_language']?.toString();
    memberPermission = json['member_permission']?.toString();
    memberReferralUrl = json['member_referral_url']?.toString();
    memberDirectline = json['member_directline']?.toString();
    memberLoginToken = json['member_login_token']?.toString();
    memberCountry = json['member_country']?.toString();
    vipLevelId = json['vip_level_id']?.toString();
    memberCountryOrigin = json['member_country_origin']?.toString();
    isTransferring = json['is_transferring']?.toString();
    memberTopupBankId = json['member_topup_bank_id']?.toString();
    vipLastUpdate = json['vip_last_update']?.toString();
    firstTimeLogin = json['first_time_login']?.toString();
    topupBankName = json['topupBankName']?.toString();
    topupBankNo = json['topupBankNo']?.toString();
    topupBank = json['topupBank']?.toString();
    countdown = json['countdown']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['topup_id'] = topupId;
    data['wallet_id'] = walletId;
    data['topup_amount'] = topupAmount;
    data['topup_amount_previous'] = topupAmountPrevious;
    data['topup_amount_balance'] = topupAmountBalance;
    data['topup_datetime'] = topupDatetime;
    data['update_datetime'] = updateDatetime;
    data['topup_status'] = topupStatus;
    data['promo_id'] = promoId;
    data['topup_receipt_url'] = topupReceiptUrl;
    data['topup_remarks'] = topupRemarks;
    data['topup_bank_id'] = topupBankId;
    data['topup_number'] = topupNumber;
    data['topup_type'] = topupType;
    data['done_by_admin_id'] = doneByAdminId;
    data['done_by_admin_name'] = doneByAdminName;
    data['topup_direct_param'] = topupDirectParam;
    data['topup_direct_response'] = topupDirectResponse;
    data['topup_unique_key'] = topupUniqueKey;
    data['topup_original_amount'] = topupOriginalAmount;
    data['topup_conversion_rate'] = topupConversionRate;
    data['topup_service_charge'] = topupServiceCharge;
    data['topup_owner_name'] = topupOwnerName;
    data['topup_method'] = topupMethod;
    data['topup_receipt'] = topupReceipt;
    data['member_id'] = memberId;
    data['wallet_balance'] = walletBalance;
    data['wallet_created_datetime'] = walletCreatedDatetime;
    data['wallet_update_datetime'] = walletUpdateDatetime;
    data['wallet_pin'] = walletPin;
    data['wallet_pin_reset_otp'] = walletPinResetOtp;
    data['wallet_country'] = walletCountry;
    data['wallet_topup_bank_id'] = walletTopupBankId;
    data['wallet_topup_bank_amount'] = walletTopupBankAmount;
    data['id'] = id;
    data['member_unique_key'] = memberUniqueKey;
    data['password'] = password;
    data['salt'] = salt;
    data['member_username'] = memberUsername;
    data['member_level'] = memberLevel;
    data['ref_upline'] = refUpline;
    data['member_main_id'] = memberMainId;
    data['member_phone_country'] = memberPhoneCountry;
    data['member_phone'] = memberPhone;
    data['member_phone_otp'] = memberPhoneOtp;
    data['member_phone_otp_salt'] = memberPhoneOtpSalt;
    data['member_phone_otp_status'] = memberPhoneOtpStatus;
    data['last_login'] = lastLogin;
    data['user_email'] = userEmail;
    data['registration_token'] = registrationToken;
    data['account_status'] = accountStatus;
    data['account_status_remarks'] = accountStatusRemarks;
    data['created_datetime'] = createdDatetime;
    data['password_otp'] = passwordOtp;
    data['password_otp_salt'] = passwordOtpSalt;
    data['password_expiry'] = passwordExpiry;
    data['bank_account_number'] = bankAccountNumber;
    data['bank_id'] = bankId;
    data['shareholder_unique_key'] = shareholderUniqueKey;
    data['bank_account_name'] = bankAccountName;
    data['pin_status'] = pinStatus;
    data['member_nickname'] = memberNickname;
    data['last_login_ip'] = lastLoginIp;
    data['member_avatar_url'] = memberAvatarUrl;
    data['member_qrcode_url'] = memberQrcodeUrl;
    data['auth_session'] = authSession;
    data['auth_expiry'] = authExpiry;
    data['member_type'] = memberType;
    data['admin_override'] = adminOverride;
    data['admin_override_expiry_datetime'] = adminOverrideExpiryDatetime;
    data['member_device_id'] = memberDeviceId;
    data['member_device'] = memberDevice;
    data['trace_history'] = traceHistory;
    data['shareholder_trace_history'] = shareholderTraceHistory;
    data['json_trace_history'] = jsonTraceHistory;
    data['member_qrcode_url_new'] = memberQrcodeUrlNew;
    data['avatar_last_update'] = avatarLastUpdate;
    data['json_shareholder_trace_history'] = jsonShareholderTraceHistory;
    data['fcm_token'] = fcmToken;
    data['member_language'] = memberLanguage;
    data['member_permission'] = memberPermission;
    data['member_referral_url'] = memberReferralUrl;
    data['member_directline'] = memberDirectline;
    data['member_login_token'] = memberLoginToken;
    data['member_country'] = memberCountry;
    data['vip_level_id'] = vipLevelId;
    data['member_country_origin'] = memberCountryOrigin;
    data['is_transferring'] = isTransferring;
    data['member_topup_bank_id'] = memberTopupBankId;
    data['vip_last_update'] = vipLastUpdate;
    data['first_time_login'] = firstTimeLogin;
    data['topupBankName'] = topupBankName;
    data['topupBankNo'] = topupBankNo;
    data['topupBank'] = topupBank;
    data['countdown'] = countdown;
    return data;
  }
}

class PendtingTopUpModelResponse {
/*
{
  "info": {
    "topup_id": "44794",
    "wallet_id": "25663",
    "topup_amount": "50.00",
    "topup_amount_previous": "11434.08",
    "topup_amount_balance": "11484.08",
    "topup_datetime": "2022-12-07 00:15:05",
    "update_datetime": null,
    "topup_status": "pending",
    "promo_id": null,
    "topup_receipt_url": "1",
    "topup_remarks": null,
    "topup_bank_id": "24",
    "topup_number": "DIRECT221207121505832785",
    "topup_type": "bank",
    "done_by_admin_id": null,
    "done_by_admin_name": null,
    "topup_direct_param": null,
    "topup_direct_response": null,
    "topup_unique_key": null,
    "topup_original_amount": null,
    "topup_conversion_rate": null,
    "topup_service_charge": null,
    "topup_owner_name": null,
    "topup_method": null,
    "topup_receipt": null,
    "member_id": "21",
    "wallet_balance": "11434.08",
    "wallet_created_datetime": "2022-05-23 17:39:23",
    "wallet_update_datetime": "2022-11-30 14:13:06",
    "wallet_pin": "000000",
    "wallet_pin_reset_otp": null,
    "wallet_country": "2",
    "wallet_topup_bank_id": null,
    "wallet_topup_bank_amount": null,
    "id": "21",
    "member_unique_key": "CvrKJgMi16n3crLQ7CRprRKYihf9epbnp29DOcd3tW4FMyNpHYUQX6V7DERpzUY4DDcz8O9pOaR4PxogOGkysdPSNPxJB2gpABtfTkloRsMKxfY8Txklj0OCtHnOUKV0kaBmNBaZNsW3eOtUNelSM3rQ6zOLoxcsgAAaqRskdqygk5lIBRrsVbuBRcHpMIMTAD8aUeNW",
    "password": "68ea8013e0b1da0f9e01f6831a5fcf9a",
    "salt": "5sUTZHtm3AAlX/c4WL5DJzU6IG0kKnFENiWTicLKV3tcLG.5EOj9WQ==",
    "member_username": "Techtest",
    "member_level": "2",
    "ref_upline": "2",
    "member_main_id": "2",
    "member_phone_country": "+60",
    "member_phone": "103600016",
    "member_phone_otp": null,
    "member_phone_otp_salt": null,
    "member_phone_otp_status": "true",
    "last_login": "2022-12-07 13:39:28",
    "user_email": null,
    "registration_token": null,
    "account_status": "active",
    "account_status_remarks": null,
    "created_datetime": "2021-04-30 19:56:17",
    "password_otp": null,
    "password_otp_salt": null,
    "password_expiry": "2022-01-21 02:30:29",
    "bank_account_number": "123456789",
    "bank_id": "2",
    "shareholder_unique_key": "aHxbKIEsjLXK6jfsr3KNEuxFMuZkTpy9BMNzxyKOLwbVUuDV7DJLX7W9IY2eI6C1Abpw5YJPXiftI4I0DIj7MBUsTdtnKHVjEqdoRDtkSpEik4XdF1ZB1bapwMZINSmzaMH3EFAbUQuxWyto7sXPhp8IKcSpUE80kY2mYMnuuk1bjPnM5ovUfM6y0Ay3YozzDxRXNANJ",
    "bank_account_name": "Ggggg",
    "pin_status": "true",
    "member_nickname": "techtest11",
    "last_login_ip": "172.70.142.184",
    "member_avatar_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/avatar/10.jpg",
    "member_qrcode_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/consumer/avatar/1675683361.png",
    "auth_session": "9TRlMTMYUzZVcdooY0K3gdIlweQxpPIi22n9XG1epfYzJHRhlOAudCY3yM29MeCzOrfycCreUGv19LwfCThIJUfDEQHDLStjkkK0iJTuF2X5BQAWl5dIEzJ92boXuLTrjDiwfp5A26xM10eRpmomHCYMQaOtJrLiYCJYXJBw2aHfZ0tcsGwp5XEyAJqZcrIJ8abfdaXu",
    "auth_expiry": "2022-12-08 13:39:28",
    "member_type": "normal",
    "admin_override": "false",
    "admin_override_expiry_datetime": null,
    "member_device_id": "58c549bc790a5ed4",
    "member_device": "Windows",
    "trace_history": "21-",
    "shareholder_trace_history": "1-",
    "json_trace_history": "[\"21\", \"\"]",
    "member_qrcode_url_new": null,
    "avatar_last_update": "2021-06-16 22:48:09",
    "json_shareholder_trace_history": "[\"1\", \"\"]",
    "fcm_token": "",
    "member_language": "en",
    "member_permission": null,
    "member_referral_url": null,
    "member_directline": "0",
    "member_login_token": null,
    "member_country": "2",
    "vip_level_id": null,
    "member_country_origin": "1",
    "is_transferring": "0",
    "member_topup_bank_id": null,
    "vip_last_update": null,
    "first_time_login": "false",
    "topupBankName": "CK Wah Global Trading",
    "topupBankNo": "514383615084",
    "topupBank": "Maybank",
    "countdown": 0
  }
} 
*/

  PendtingTopUpModelResponseInfo? info;

  PendtingTopUpModelResponse({
    this.info,
  });
  PendtingTopUpModelResponse.fromJson(Map<String, dynamic> json) {
    info = (json['info'] != null)
        ? PendtingTopUpModelResponseInfo.fromJson(json['info'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (info != null) {
      data['info'] = info!.toJson();
    }
    return data;
  }
}

class PendtingTopUpModel {
/*
{
  "msg": "There is a pending topup.",
  "response": {
    "info": {
      "topup_id": "44794",
      "wallet_id": "25663",
      "topup_amount": "50.00",
      "topup_amount_previous": "11434.08",
      "topup_amount_balance": "11484.08",
      "topup_datetime": "2022-12-07 00:15:05",
      "update_datetime": null,
      "topup_status": "pending",
      "promo_id": null,
      "topup_receipt_url": "1",
      "topup_remarks": null,
      "topup_bank_id": "24",
      "topup_number": "DIRECT221207121505832785",
      "topup_type": "bank",
      "done_by_admin_id": null,
      "done_by_admin_name": null,
      "topup_direct_param": null,
      "topup_direct_response": null,
      "topup_unique_key": null,
      "topup_original_amount": null,
      "topup_conversion_rate": null,
      "topup_service_charge": null,
      "topup_owner_name": null,
      "topup_method": null,
      "topup_receipt": null,
      "member_id": "21",
      "wallet_balance": "11434.08",
      "wallet_created_datetime": "2022-05-23 17:39:23",
      "wallet_update_datetime": "2022-11-30 14:13:06",
      "wallet_pin": "000000",
      "wallet_pin_reset_otp": null,
      "wallet_country": "2",
      "wallet_topup_bank_id": null,
      "wallet_topup_bank_amount": null,
      "id": "21",
      "member_unique_key": "CvrKJgMi16n3crLQ7CRprRKYihf9epbnp29DOcd3tW4FMyNpHYUQX6V7DERpzUY4DDcz8O9pOaR4PxogOGkysdPSNPxJB2gpABtfTkloRsMKxfY8Txklj0OCtHnOUKV0kaBmNBaZNsW3eOtUNelSM3rQ6zOLoxcsgAAaqRskdqygk5lIBRrsVbuBRcHpMIMTAD8aUeNW",
      "password": "68ea8013e0b1da0f9e01f6831a5fcf9a",
      "salt": "5sUTZHtm3AAlX/c4WL5DJzU6IG0kKnFENiWTicLKV3tcLG.5EOj9WQ==",
      "member_username": "Techtest",
      "member_level": "2",
      "ref_upline": "2",
      "member_main_id": "2",
      "member_phone_country": "+60",
      "member_phone": "103600016",
      "member_phone_otp": null,
      "member_phone_otp_salt": null,
      "member_phone_otp_status": "true",
      "last_login": "2022-12-07 13:39:28",
      "user_email": null,
      "registration_token": null,
      "account_status": "active",
      "account_status_remarks": null,
      "created_datetime": "2021-04-30 19:56:17",
      "password_otp": null,
      "password_otp_salt": null,
      "password_expiry": "2022-01-21 02:30:29",
      "bank_account_number": "123456789",
      "bank_id": "2",
      "shareholder_unique_key": "aHxbKIEsjLXK6jfsr3KNEuxFMuZkTpy9BMNzxyKOLwbVUuDV7DJLX7W9IY2eI6C1Abpw5YJPXiftI4I0DIj7MBUsTdtnKHVjEqdoRDtkSpEik4XdF1ZB1bapwMZINSmzaMH3EFAbUQuxWyto7sXPhp8IKcSpUE80kY2mYMnuuk1bjPnM5ovUfM6y0Ay3YozzDxRXNANJ",
      "bank_account_name": "Ggggg",
      "pin_status": "true",
      "member_nickname": "techtest11",
      "last_login_ip": "172.70.142.184",
      "member_avatar_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/avatar/10.jpg",
      "member_qrcode_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/consumer/avatar/1675683361.png",
      "auth_session": "9TRlMTMYUzZVcdooY0K3gdIlweQxpPIi22n9XG1epfYzJHRhlOAudCY3yM29MeCzOrfycCreUGv19LwfCThIJUfDEQHDLStjkkK0iJTuF2X5BQAWl5dIEzJ92boXuLTrjDiwfp5A26xM10eRpmomHCYMQaOtJrLiYCJYXJBw2aHfZ0tcsGwp5XEyAJqZcrIJ8abfdaXu",
      "auth_expiry": "2022-12-08 13:39:28",
      "member_type": "normal",
      "admin_override": "false",
      "admin_override_expiry_datetime": null,
      "member_device_id": "58c549bc790a5ed4",
      "member_device": "Windows",
      "trace_history": "21-",
      "shareholder_trace_history": "1-",
      "json_trace_history": "[\"21\", \"\"]",
      "member_qrcode_url_new": null,
      "avatar_last_update": "2021-06-16 22:48:09",
      "json_shareholder_trace_history": "[\"1\", \"\"]",
      "fcm_token": "",
      "member_language": "en",
      "member_permission": null,
      "member_referral_url": null,
      "member_directline": "0",
      "member_login_token": null,
      "member_country": "2",
      "vip_level_id": null,
      "member_country_origin": "1",
      "is_transferring": "0",
      "member_topup_bank_id": null,
      "vip_last_update": null,
      "first_time_login": "false",
      "topupBankName": "CK Wah Global Trading",
      "topupBankNo": "514383615084",
      "topupBank": "Maybank",
      "countdown": 0
    }
  }
} 
*/

  String? msg;
  PendtingTopUpModelResponse? response;

  PendtingTopUpModel({
    this.msg,
    this.response,
  });
  PendtingTopUpModel.fromJson(Map<String, dynamic> json) {
    msg = json['msg']?.toString();
    response = (json['response'] != null)
        ? PendtingTopUpModelResponse.fromJson(json['response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['msg'] = msg;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
