///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ContactsModelResponseList {
/*
{
  "friend_id": "74728",
  "member_id": "21",
  "friend_member_id": "1805",
  "friend_status": "active",
  "friend_nickname": null,
  "created_datetime": "2021-06-11 00:28:36",
  "modified_datetime": "2021-06-11 00:28:36",
  "friend_unique_key": "OVZY1xHD4TdkRbqxxRyclbKP17JDLIb3cDF142vhWDXLq5oK7NgKVLN08lL6IBP671gZA0tK4v83laO4UWqDIWi119YSlA6dw8f2sUHwAuvUpC5kwuHPlWyjV7QDISgxSLcqUCx28wMysK6Cl5PUZLz3QFUZVFcEFQvlgEWLD8vjMdvfApgUlIXMqh3usVdnt91tuQEM",
  "original": "original",
  "member_unique_key": "R5WsFK8IW9hIuOJ7pTo2IM8LfFuJbnVutvWOlHI66zaBEdQKlZdfAk3SFu80SpH6DWqHgb6yJ7HK3Cx3QTRXRvCYOAaP9yqh00u3uPToAV19UKL4uYg8QN18oJgsDAPL9169ufJUiQbyWOqLcNRYgwqnEqM5RS6kViBlYK0FAh6woXjvKpmQHTIPeiqwmbIXEd1eO9JO",
  "member_username": "developer2",
  "member_avatar_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/avatar/03.jpg",
  "new_messages_count": "0"
} 
*/

  String? friendId;
  String? memberId;
  String? friendMemberId;
  String? friendStatus;
  String? friendNickname;
  String? createdDatetime;
  String? modifiedDatetime;
  String? friendUniqueKey;
  String? original;
  String? memberUniqueKey;
  String? memberUsername;
  String? memberAvatarUrl;
  String? newMessagesCount;

  ContactsModelResponseList({
    this.friendId,
    this.memberId,
    this.friendMemberId,
    this.friendStatus,
    this.friendNickname,
    this.createdDatetime,
    this.modifiedDatetime,
    this.friendUniqueKey,
    this.original,
    this.memberUniqueKey,
    this.memberUsername,
    this.memberAvatarUrl,
    this.newMessagesCount,
  });
  ContactsModelResponseList.fromJson(Map<String, dynamic> json) {
    friendId = json['friend_id']?.toString();
    memberId = json['member_id']?.toString();
    friendMemberId = json['friend_member_id']?.toString();
    friendStatus = json['friend_status']?.toString();
    friendNickname = json['friend_nickname']?.toString();
    createdDatetime = json['created_datetime']?.toString();
    modifiedDatetime = json['modified_datetime']?.toString();
    friendUniqueKey = json['friend_unique_key']?.toString();
    original = json['original']?.toString();
    memberUniqueKey = json['member_unique_key']?.toString();
    memberUsername = json['member_username']?.toString();
    memberAvatarUrl = json['member_avatar_url']?.toString();
    newMessagesCount = json['new_messages_count']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['friend_id'] = friendId;
    data['member_id'] = memberId;
    data['friend_member_id'] = friendMemberId;
    data['friend_status'] = friendStatus;
    data['friend_nickname'] = friendNickname;
    data['created_datetime'] = createdDatetime;
    data['modified_datetime'] = modifiedDatetime;
    data['friend_unique_key'] = friendUniqueKey;
    data['original'] = original;
    data['member_unique_key'] = memberUniqueKey;
    data['member_username'] = memberUsername;
    data['member_avatar_url'] = memberAvatarUrl;
    data['new_messages_count'] = newMessagesCount;
    return data;
  }
}

class ContactsModelResponse {
/*
{
  "list": [
    {
      "friend_id": "74728",
      "member_id": "21",
      "friend_member_id": "1805",
      "friend_status": "active",
      "friend_nickname": null,
      "created_datetime": "2021-06-11 00:28:36",
      "modified_datetime": "2021-06-11 00:28:36",
      "friend_unique_key": "OVZY1xHD4TdkRbqxxRyclbKP17JDLIb3cDF142vhWDXLq5oK7NgKVLN08lL6IBP671gZA0tK4v83laO4UWqDIWi119YSlA6dw8f2sUHwAuvUpC5kwuHPlWyjV7QDISgxSLcqUCx28wMysK6Cl5PUZLz3QFUZVFcEFQvlgEWLD8vjMdvfApgUlIXMqh3usVdnt91tuQEM",
      "original": "original",
      "member_unique_key": "R5WsFK8IW9hIuOJ7pTo2IM8LfFuJbnVutvWOlHI66zaBEdQKlZdfAk3SFu80SpH6DWqHgb6yJ7HK3Cx3QTRXRvCYOAaP9yqh00u3uPToAV19UKL4uYg8QN18oJgsDAPL9169ufJUiQbyWOqLcNRYgwqnEqM5RS6kViBlYK0FAh6woXjvKpmQHTIPeiqwmbIXEd1eO9JO",
      "member_username": "developer2",
      "member_avatar_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/avatar/03.jpg",
      "new_messages_count": "0"
    }
  ]
} 
*/

  List<ContactsModelResponseList?>? list;

  ContactsModelResponse({
    this.list,
  });
  ContactsModelResponse.fromJson(Map<String, dynamic> json) {
    if (json['list'] != null) {
      final v = json['list'];
      final arr0 = <ContactsModelResponseList>[];
      v.forEach((v) {
        arr0.add(ContactsModelResponseList.fromJson(v));
      });
      list = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (list != null) {
      final v = list;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['list'] = arr0;
    }
    return data;
  }
}

class ContactsModel {
/*
{
  "msg": "List retrieved",
  "response": {
    "list": [
      {
        "friend_id": "74728",
        "member_id": "21",
        "friend_member_id": "1805",
        "friend_status": "active",
        "friend_nickname": null,
        "created_datetime": "2021-06-11 00:28:36",
        "modified_datetime": "2021-06-11 00:28:36",
        "friend_unique_key": "OVZY1xHD4TdkRbqxxRyclbKP17JDLIb3cDF142vhWDXLq5oK7NgKVLN08lL6IBP671gZA0tK4v83laO4UWqDIWi119YSlA6dw8f2sUHwAuvUpC5kwuHPlWyjV7QDISgxSLcqUCx28wMysK6Cl5PUZLz3QFUZVFcEFQvlgEWLD8vjMdvfApgUlIXMqh3usVdnt91tuQEM",
        "original": "original",
        "member_unique_key": "R5WsFK8IW9hIuOJ7pTo2IM8LfFuJbnVutvWOlHI66zaBEdQKlZdfAk3SFu80SpH6DWqHgb6yJ7HK3Cx3QTRXRvCYOAaP9yqh00u3uPToAV19UKL4uYg8QN18oJgsDAPL9169ufJUiQbyWOqLcNRYgwqnEqM5RS6kViBlYK0FAh6woXjvKpmQHTIPeiqwmbIXEd1eO9JO",
        "member_username": "developer2",
        "member_avatar_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/avatar/03.jpg",
        "new_messages_count": "0"
      }
    ]
  }
} 
*/

  String? msg;
  ContactsModelResponse? response;

  ContactsModel({
    this.msg,
    this.response,
  });
  ContactsModel.fromJson(Map<String, dynamic> json) {
    msg = json['msg']?.toString();
    response = (json['response'] != null)
        ? ContactsModelResponse.fromJson(json['response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['msg'] = msg;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
