///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SearchFriendModelResponseFriend {
/*
{
  "id": "25784",
  "member_unique_key": "ULHrzxpJGnQBNqaS95ttbRdQ7BA9XoQTeRmnsrXHV9o7V96w2KktS2IgZ6KRQrPKbkdmR1ohRc7UQbr27log2amjFqk2ZL99G4ueE90drNCoyIAW5MnKwPiUjD4AOgkHwSTO9Iz3wWWBpAjb2Q5vHAlMzrbc6cZmp20ujKrDycWYzs7gFFfksm9YqqsMydThjNyuk4Z0",
  "password": "1e18732f518cfb10bb380a0a7e2642e5",
  "salt": "nfiQ6viu8L2gnyi0GIHduSOchSC.Av9zXJ5TdEwEuj7XxrCNlRfxTg==",
  "member_username": "ali051",
  "member_level": "2",
  "ref_upline": "1",
  "member_main_id": "11",
  "member_phone_country": "+60",
  "member_phone": "123456789",
  "member_phone_otp": null,
  "member_phone_otp_salt": "c3kz34h/FC48w7nPTNlONsFePDM=",
  "member_phone_otp_status": "true",
  "last_login": null,
  "user_email": null,
  "registration_token": null,
  "account_status": "active",
  "account_status_remarks": null,
  "created_datetime": "2022-11-08 14:00:42",
  "password_otp": null,
  "password_otp_salt": null,
  "password_expiry": null,
  "bank_account_number": null,
  "bank_id": null,
  "shareholder_unique_key": "aHxbKIEsjLXK6jfsr3KNEuxFMuZkTpy9BMNzxyKOLwbVUuDV7DJLX7W9IY2eI6C1Abpw5YJPXiftI4I0DIj7MBUsTdtnKHVjEqdoRDtkSpEik4XdF1ZB1bapwMZINSmzaMH3EFAbUQuxWyto7sXPhp8IKcSpUE80kY2mYMnuuk1bjPnM5ovUfM6y0Ay3YozzDxRXNANJ",
  "bank_account_name": null,
  "pin_status": "true",
  "member_nickname": null,
  "last_login_ip": null,
  "member_avatar_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/avatar/34.jpg",
  "member_qrcode_url": "https://imagedelivery.net/8F4PR10vncj5Q6UoH8dlPg/4290a3ef-52fd-40bb-0b8d-bdc4cdb1e500/public",
  "auth_session": "UbBWZgOohnKXdA2eMUBQigKaj3LzjGQopPuhSETVkchd8GsLjuXH6VD0FmqDeeItmOizTFga8NgeVGnFOYp9xrtcSEYkJk5ODZsmDIt25KK3Sx83AUTaMOJSWFJaTZu35ntM0J5Ni9UiLOXh7QbwrtAI0MnDwKRmttg05qCcsJV81Q7PvoyQAn9DQFPUaKaWf2x9zy6j",
  "auth_expiry": "2022-11-16 23:46:36",
  "member_type": "normal",
  "admin_override": "false",
  "admin_override_expiry_datetime": null,
  "member_device_id": "",
  "member_device": null,
  "trace_history": "1-25784-",
  "shareholder_trace_history": null,
  "json_trace_history": null,
  "member_qrcode_url_new": null,
  "avatar_last_update": null,
  "json_shareholder_trace_history": null,
  "fcm_token": null,
  "member_language": "en",
  "member_permission": null,
  "member_referral_url": "https://member.luckytown.online/download/app?ref=ali051",
  "member_directline": "0",
  "member_login_token": null,
  "member_country": "1",
  "vip_level_id": null,
  "member_country_origin": "1",
  "wallet_pin": null,
  "wallet_pin_reset_otp": null,
  "is_transferring": "0",
  "member_topup_bank_id": null,
  "vip_last_update": null,
  "first_time_login": "true",
  "walletBalance": "0.00",
  "coinBalance": "0.00",
  "interestBalance": "0.00",
  "total_deposit": null,
  "total_withdraw": null,
  "total_transfer_out": null,
  "total_transfer_in": null,
  "total_interest": null,
  "country_id": "1",
  "country_name": "Malaysia",
  "country_code": "MYR",
  "country_url": "https://suncity.s3.ap-southeast-1.amazonaws.com/country/MYR-flag.png"
} 
*/

  String? id;
  String? memberUniqueKey;
  String? password;
  String? salt;
  String? memberUsername;
  String? memberLevel;
  String? refUpline;
  String? memberMainId;
  String? memberPhoneCountry;
  String? memberPhone;
  String? memberPhoneOtp;
  String? memberPhoneOtpSalt;
  String? memberPhoneOtpStatus;
  String? lastLogin;
  String? userEmail;
  String? registrationToken;
  String? accountStatus;
  String? accountStatusRemarks;
  String? createdDatetime;
  String? passwordOtp;
  String? passwordOtpSalt;
  String? passwordExpiry;
  String? bankAccountNumber;
  String? bankId;
  String? shareholderUniqueKey;
  String? bankAccountName;
  String? pinStatus;
  String? memberNickname;
  String? lastLoginIp;
  String? memberAvatarUrl;
  String? memberQrcodeUrl;
  String? authSession;
  String? authExpiry;
  String? memberType;
  String? adminOverride;
  String? adminOverrideExpiryDatetime;
  String? memberDeviceId;
  String? memberDevice;
  String? traceHistory;
  String? shareholderTraceHistory;
  String? jsonTraceHistory;
  String? memberQrcodeUrlNew;
  String? avatarLastUpdate;
  String? jsonShareholderTraceHistory;
  String? fcmToken;
  String? memberLanguage;
  String? memberPermission;
  String? memberReferralUrl;
  String? memberDirectline;
  String? memberLoginToken;
  String? memberCountry;
  String? vipLevelId;
  String? memberCountryOrigin;
  String? walletPin;
  String? walletPinResetOtp;
  String? isTransferring;
  String? memberTopupBankId;
  String? vipLastUpdate;
  String? firstTimeLogin;
  String? walletBalance;
  String? coinBalance;
  String? interestBalance;
  String? totalDeposit;
  String? totalWithdraw;
  String? totalTransferOut;
  String? totalTransferIn;
  String? totalInterest;
  String? countryId;
  String? countryName;
  String? countryCode;
  String? countryUrl;

  SearchFriendModelResponseFriend({
    this.id,
    this.memberUniqueKey,
    this.password,
    this.salt,
    this.memberUsername,
    this.memberLevel,
    this.refUpline,
    this.memberMainId,
    this.memberPhoneCountry,
    this.memberPhone,
    this.memberPhoneOtp,
    this.memberPhoneOtpSalt,
    this.memberPhoneOtpStatus,
    this.lastLogin,
    this.userEmail,
    this.registrationToken,
    this.accountStatus,
    this.accountStatusRemarks,
    this.createdDatetime,
    this.passwordOtp,
    this.passwordOtpSalt,
    this.passwordExpiry,
    this.bankAccountNumber,
    this.bankId,
    this.shareholderUniqueKey,
    this.bankAccountName,
    this.pinStatus,
    this.memberNickname,
    this.lastLoginIp,
    this.memberAvatarUrl,
    this.memberQrcodeUrl,
    this.authSession,
    this.authExpiry,
    this.memberType,
    this.adminOverride,
    this.adminOverrideExpiryDatetime,
    this.memberDeviceId,
    this.memberDevice,
    this.traceHistory,
    this.shareholderTraceHistory,
    this.jsonTraceHistory,
    this.memberQrcodeUrlNew,
    this.avatarLastUpdate,
    this.jsonShareholderTraceHistory,
    this.fcmToken,
    this.memberLanguage,
    this.memberPermission,
    this.memberReferralUrl,
    this.memberDirectline,
    this.memberLoginToken,
    this.memberCountry,
    this.vipLevelId,
    this.memberCountryOrigin,
    this.walletPin,
    this.walletPinResetOtp,
    this.isTransferring,
    this.memberTopupBankId,
    this.vipLastUpdate,
    this.firstTimeLogin,
    this.walletBalance,
    this.coinBalance,
    this.interestBalance,
    this.totalDeposit,
    this.totalWithdraw,
    this.totalTransferOut,
    this.totalTransferIn,
    this.totalInterest,
    this.countryId,
    this.countryName,
    this.countryCode,
    this.countryUrl,
  });
  SearchFriendModelResponseFriend.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    memberUniqueKey = json['member_unique_key']?.toString();
    password = json['password']?.toString();
    salt = json['salt']?.toString();
    memberUsername = json['member_username']?.toString();
    memberLevel = json['member_level']?.toString();
    refUpline = json['ref_upline']?.toString();
    memberMainId = json['member_main_id']?.toString();
    memberPhoneCountry = json['member_phone_country']?.toString();
    memberPhone = json['member_phone']?.toString();
    memberPhoneOtp = json['member_phone_otp']?.toString();
    memberPhoneOtpSalt = json['member_phone_otp_salt']?.toString();
    memberPhoneOtpStatus = json['member_phone_otp_status']?.toString();
    lastLogin = json['last_login']?.toString();
    userEmail = json['user_email']?.toString();
    registrationToken = json['registration_token']?.toString();
    accountStatus = json['account_status']?.toString();
    accountStatusRemarks = json['account_status_remarks']?.toString();
    createdDatetime = json['created_datetime']?.toString();
    passwordOtp = json['password_otp']?.toString();
    passwordOtpSalt = json['password_otp_salt']?.toString();
    passwordExpiry = json['password_expiry']?.toString();
    bankAccountNumber = json['bank_account_number']?.toString();
    bankId = json['bank_id']?.toString();
    shareholderUniqueKey = json['shareholder_unique_key']?.toString();
    bankAccountName = json['bank_account_name']?.toString();
    pinStatus = json['pin_status']?.toString();
    memberNickname = json['member_nickname']?.toString();
    lastLoginIp = json['last_login_ip']?.toString();
    memberAvatarUrl = json['member_avatar_url']?.toString();
    memberQrcodeUrl = json['member_qrcode_url']?.toString();
    authSession = json['auth_session']?.toString();
    authExpiry = json['auth_expiry']?.toString();
    memberType = json['member_type']?.toString();
    adminOverride = json['admin_override']?.toString();
    adminOverrideExpiryDatetime =
        json['admin_override_expiry_datetime']?.toString();
    memberDeviceId = json['member_device_id']?.toString();
    memberDevice = json['member_device']?.toString();
    traceHistory = json['trace_history']?.toString();
    shareholderTraceHistory = json['shareholder_trace_history']?.toString();
    jsonTraceHistory = json['json_trace_history']?.toString();
    memberQrcodeUrlNew = json['member_qrcode_url_new']?.toString();
    avatarLastUpdate = json['avatar_last_update']?.toString();
    jsonShareholderTraceHistory =
        json['json_shareholder_trace_history']?.toString();
    fcmToken = json['fcm_token']?.toString();
    memberLanguage = json['member_language']?.toString();
    memberPermission = json['member_permission']?.toString();
    memberReferralUrl = json['member_referral_url']?.toString();
    memberDirectline = json['member_directline']?.toString();
    memberLoginToken = json['member_login_token']?.toString();
    memberCountry = json['member_country']?.toString();
    vipLevelId = json['vip_level_id']?.toString();
    memberCountryOrigin = json['member_country_origin']?.toString();
    walletPin = json['wallet_pin']?.toString();
    walletPinResetOtp = json['wallet_pin_reset_otp']?.toString();
    isTransferring = json['is_transferring']?.toString();
    memberTopupBankId = json['member_topup_bank_id']?.toString();
    vipLastUpdate = json['vip_last_update']?.toString();
    firstTimeLogin = json['first_time_login']?.toString();
    walletBalance = json['walletBalance']?.toString();
    coinBalance = json['coinBalance']?.toString();
    interestBalance = json['interestBalance']?.toString();
    totalDeposit = json['total_deposit']?.toString();
    totalWithdraw = json['total_withdraw']?.toString();
    totalTransferOut = json['total_transfer_out']?.toString();
    totalTransferIn = json['total_transfer_in']?.toString();
    totalInterest = json['total_interest']?.toString();
    countryId = json['country_id']?.toString();
    countryName = json['country_name']?.toString();
    countryCode = json['country_code']?.toString();
    countryUrl = json['country_url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['member_unique_key'] = memberUniqueKey;
    data['password'] = password;
    data['salt'] = salt;
    data['member_username'] = memberUsername;
    data['member_level'] = memberLevel;
    data['ref_upline'] = refUpline;
    data['member_main_id'] = memberMainId;
    data['member_phone_country'] = memberPhoneCountry;
    data['member_phone'] = memberPhone;
    data['member_phone_otp'] = memberPhoneOtp;
    data['member_phone_otp_salt'] = memberPhoneOtpSalt;
    data['member_phone_otp_status'] = memberPhoneOtpStatus;
    data['last_login'] = lastLogin;
    data['user_email'] = userEmail;
    data['registration_token'] = registrationToken;
    data['account_status'] = accountStatus;
    data['account_status_remarks'] = accountStatusRemarks;
    data['created_datetime'] = createdDatetime;
    data['password_otp'] = passwordOtp;
    data['password_otp_salt'] = passwordOtpSalt;
    data['password_expiry'] = passwordExpiry;
    data['bank_account_number'] = bankAccountNumber;
    data['bank_id'] = bankId;
    data['shareholder_unique_key'] = shareholderUniqueKey;
    data['bank_account_name'] = bankAccountName;
    data['pin_status'] = pinStatus;
    data['member_nickname'] = memberNickname;
    data['last_login_ip'] = lastLoginIp;
    data['member_avatar_url'] = memberAvatarUrl;
    data['member_qrcode_url'] = memberQrcodeUrl;
    data['auth_session'] = authSession;
    data['auth_expiry'] = authExpiry;
    data['member_type'] = memberType;
    data['admin_override'] = adminOverride;
    data['admin_override_expiry_datetime'] = adminOverrideExpiryDatetime;
    data['member_device_id'] = memberDeviceId;
    data['member_device'] = memberDevice;
    data['trace_history'] = traceHistory;
    data['shareholder_trace_history'] = shareholderTraceHistory;
    data['json_trace_history'] = jsonTraceHistory;
    data['member_qrcode_url_new'] = memberQrcodeUrlNew;
    data['avatar_last_update'] = avatarLastUpdate;
    data['json_shareholder_trace_history'] = jsonShareholderTraceHistory;
    data['fcm_token'] = fcmToken;
    data['member_language'] = memberLanguage;
    data['member_permission'] = memberPermission;
    data['member_referral_url'] = memberReferralUrl;
    data['member_directline'] = memberDirectline;
    data['member_login_token'] = memberLoginToken;
    data['member_country'] = memberCountry;
    data['vip_level_id'] = vipLevelId;
    data['member_country_origin'] = memberCountryOrigin;
    data['wallet_pin'] = walletPin;
    data['wallet_pin_reset_otp'] = walletPinResetOtp;
    data['is_transferring'] = isTransferring;
    data['member_topup_bank_id'] = memberTopupBankId;
    data['vip_last_update'] = vipLastUpdate;
    data['first_time_login'] = firstTimeLogin;
    data['walletBalance'] = walletBalance;
    data['coinBalance'] = coinBalance;
    data['interestBalance'] = interestBalance;
    data['total_deposit'] = totalDeposit;
    data['total_withdraw'] = totalWithdraw;
    data['total_transfer_out'] = totalTransferOut;
    data['total_transfer_in'] = totalTransferIn;
    data['total_interest'] = totalInterest;
    data['country_id'] = countryId;
    data['country_name'] = countryName;
    data['country_code'] = countryCode;
    data['country_url'] = countryUrl;
    return data;
  }
}

class SearchFriendModelResponse {
/*
{
  "friend": {
    "id": "25784",
    "member_unique_key": "ULHrzxpJGnQBNqaS95ttbRdQ7BA9XoQTeRmnsrXHV9o7V96w2KktS2IgZ6KRQrPKbkdmR1ohRc7UQbr27log2amjFqk2ZL99G4ueE90drNCoyIAW5MnKwPiUjD4AOgkHwSTO9Iz3wWWBpAjb2Q5vHAlMzrbc6cZmp20ujKrDycWYzs7gFFfksm9YqqsMydThjNyuk4Z0",
    "password": "1e18732f518cfb10bb380a0a7e2642e5",
    "salt": "nfiQ6viu8L2gnyi0GIHduSOchSC.Av9zXJ5TdEwEuj7XxrCNlRfxTg==",
    "member_username": "ali051",
    "member_level": "2",
    "ref_upline": "1",
    "member_main_id": "11",
    "member_phone_country": "+60",
    "member_phone": "123456789",
    "member_phone_otp": null,
    "member_phone_otp_salt": "c3kz34h/FC48w7nPTNlONsFePDM=",
    "member_phone_otp_status": "true",
    "last_login": null,
    "user_email": null,
    "registration_token": null,
    "account_status": "active",
    "account_status_remarks": null,
    "created_datetime": "2022-11-08 14:00:42",
    "password_otp": null,
    "password_otp_salt": null,
    "password_expiry": null,
    "bank_account_number": null,
    "bank_id": null,
    "shareholder_unique_key": "aHxbKIEsjLXK6jfsr3KNEuxFMuZkTpy9BMNzxyKOLwbVUuDV7DJLX7W9IY2eI6C1Abpw5YJPXiftI4I0DIj7MBUsTdtnKHVjEqdoRDtkSpEik4XdF1ZB1bapwMZINSmzaMH3EFAbUQuxWyto7sXPhp8IKcSpUE80kY2mYMnuuk1bjPnM5ovUfM6y0Ay3YozzDxRXNANJ",
    "bank_account_name": null,
    "pin_status": "true",
    "member_nickname": null,
    "last_login_ip": null,
    "member_avatar_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/avatar/34.jpg",
    "member_qrcode_url": "https://imagedelivery.net/8F4PR10vncj5Q6UoH8dlPg/4290a3ef-52fd-40bb-0b8d-bdc4cdb1e500/public",
    "auth_session": "UbBWZgOohnKXdA2eMUBQigKaj3LzjGQopPuhSETVkchd8GsLjuXH6VD0FmqDeeItmOizTFga8NgeVGnFOYp9xrtcSEYkJk5ODZsmDIt25KK3Sx83AUTaMOJSWFJaTZu35ntM0J5Ni9UiLOXh7QbwrtAI0MnDwKRmttg05qCcsJV81Q7PvoyQAn9DQFPUaKaWf2x9zy6j",
    "auth_expiry": "2022-11-16 23:46:36",
    "member_type": "normal",
    "admin_override": "false",
    "admin_override_expiry_datetime": null,
    "member_device_id": "",
    "member_device": null,
    "trace_history": "1-25784-",
    "shareholder_trace_history": null,
    "json_trace_history": null,
    "member_qrcode_url_new": null,
    "avatar_last_update": null,
    "json_shareholder_trace_history": null,
    "fcm_token": null,
    "member_language": "en",
    "member_permission": null,
    "member_referral_url": "https://member.luckytown.online/download/app?ref=ali051",
    "member_directline": "0",
    "member_login_token": null,
    "member_country": "1",
    "vip_level_id": null,
    "member_country_origin": "1",
    "wallet_pin": null,
    "wallet_pin_reset_otp": null,
    "is_transferring": "0",
    "member_topup_bank_id": null,
    "vip_last_update": null,
    "first_time_login": "true",
    "walletBalance": "0.00",
    "coinBalance": "0.00",
    "interestBalance": "0.00",
    "total_deposit": null,
    "total_withdraw": null,
    "total_transfer_out": null,
    "total_transfer_in": null,
    "total_interest": null,
    "country_id": "1",
    "country_name": "Malaysia",
    "country_code": "MYR",
    "country_url": "https://suncity.s3.ap-southeast-1.amazonaws.com/country/MYR-flag.png"
  }
} 
*/

  SearchFriendModelResponseFriend? friend;

  SearchFriendModelResponse({
    this.friend,
  });
  SearchFriendModelResponse.fromJson(Map<String, dynamic> json) {
    friend = (json['friend'] != null)
        ? SearchFriendModelResponseFriend.fromJson(json['friend'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (friend != null) {
      data['friend'] = friend!.toJson();
    }
    return data;
  }
}

class SearchFriendModel {
/*
{
  "msg": "Username found",
  "response": {
    "friend": {
      "id": "25784",
      "member_unique_key": "ULHrzxpJGnQBNqaS95ttbRdQ7BA9XoQTeRmnsrXHV9o7V96w2KktS2IgZ6KRQrPKbkdmR1ohRc7UQbr27log2amjFqk2ZL99G4ueE90drNCoyIAW5MnKwPiUjD4AOgkHwSTO9Iz3wWWBpAjb2Q5vHAlMzrbc6cZmp20ujKrDycWYzs7gFFfksm9YqqsMydThjNyuk4Z0",
      "password": "1e18732f518cfb10bb380a0a7e2642e5",
      "salt": "nfiQ6viu8L2gnyi0GIHduSOchSC.Av9zXJ5TdEwEuj7XxrCNlRfxTg==",
      "member_username": "ali051",
      "member_level": "2",
      "ref_upline": "1",
      "member_main_id": "11",
      "member_phone_country": "+60",
      "member_phone": "123456789",
      "member_phone_otp": null,
      "member_phone_otp_salt": "c3kz34h/FC48w7nPTNlONsFePDM=",
      "member_phone_otp_status": "true",
      "last_login": null,
      "user_email": null,
      "registration_token": null,
      "account_status": "active",
      "account_status_remarks": null,
      "created_datetime": "2022-11-08 14:00:42",
      "password_otp": null,
      "password_otp_salt": null,
      "password_expiry": null,
      "bank_account_number": null,
      "bank_id": null,
      "shareholder_unique_key": "aHxbKIEsjLXK6jfsr3KNEuxFMuZkTpy9BMNzxyKOLwbVUuDV7DJLX7W9IY2eI6C1Abpw5YJPXiftI4I0DIj7MBUsTdtnKHVjEqdoRDtkSpEik4XdF1ZB1bapwMZINSmzaMH3EFAbUQuxWyto7sXPhp8IKcSpUE80kY2mYMnuuk1bjPnM5ovUfM6y0Ay3YozzDxRXNANJ",
      "bank_account_name": null,
      "pin_status": "true",
      "member_nickname": null,
      "last_login_ip": null,
      "member_avatar_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/avatar/34.jpg",
      "member_qrcode_url": "https://imagedelivery.net/8F4PR10vncj5Q6UoH8dlPg/4290a3ef-52fd-40bb-0b8d-bdc4cdb1e500/public",
      "auth_session": "UbBWZgOohnKXdA2eMUBQigKaj3LzjGQopPuhSETVkchd8GsLjuXH6VD0FmqDeeItmOizTFga8NgeVGnFOYp9xrtcSEYkJk5ODZsmDIt25KK3Sx83AUTaMOJSWFJaTZu35ntM0J5Ni9UiLOXh7QbwrtAI0MnDwKRmttg05qCcsJV81Q7PvoyQAn9DQFPUaKaWf2x9zy6j",
      "auth_expiry": "2022-11-16 23:46:36",
      "member_type": "normal",
      "admin_override": "false",
      "admin_override_expiry_datetime": null,
      "member_device_id": "",
      "member_device": null,
      "trace_history": "1-25784-",
      "shareholder_trace_history": null,
      "json_trace_history": null,
      "member_qrcode_url_new": null,
      "avatar_last_update": null,
      "json_shareholder_trace_history": null,
      "fcm_token": null,
      "member_language": "en",
      "member_permission": null,
      "member_referral_url": "https://member.luckytown.online/download/app?ref=ali051",
      "member_directline": "0",
      "member_login_token": null,
      "member_country": "1",
      "vip_level_id": null,
      "member_country_origin": "1",
      "wallet_pin": null,
      "wallet_pin_reset_otp": null,
      "is_transferring": "0",
      "member_topup_bank_id": null,
      "vip_last_update": null,
      "first_time_login": "true",
      "walletBalance": "0.00",
      "coinBalance": "0.00",
      "interestBalance": "0.00",
      "total_deposit": null,
      "total_withdraw": null,
      "total_transfer_out": null,
      "total_transfer_in": null,
      "total_interest": null,
      "country_id": "1",
      "country_name": "Malaysia",
      "country_code": "MYR",
      "country_url": "https://suncity.s3.ap-southeast-1.amazonaws.com/country/MYR-flag.png"
    }
  }
} 
*/

  String? msg;
  SearchFriendModelResponse? response;

  SearchFriendModel({
    this.msg,
    this.response,
  });
  SearchFriendModel.fromJson(Map<String, dynamic> json) {
    msg = json['msg']?.toString();
    response = (json['response'] != null)
        ? SearchFriendModelResponse.fromJson(json['response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['msg'] = msg;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
