///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AvailableCreditsResponseProductDetail {
/*
{
  "product_id": "99",
  "product_name": "THREESING",
  "product_status": "active",
  "product_category_group": "Sport",
  "product_category": "SPORT",
  "product_desc": "THREESING",
  "product_grouping": null,
  "product_image_url": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/3sing.jpg",
  "product_coin_entitled": "false",
  "product_provider": "THREESING",
  "product_percentage": "10.00",
  "product_image_url_grey": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/Bnw/3sing-bnw.jpg",
  "product_avenger_direct": "false",
  "product_main_commission_percentage": "0.20",
  "product_upline_commission_percentage": "0.30",
  "product_self_commission_percentage": "0.50",
  "product_test": "true",
  "product_sequence": "43",
  "ping_with_cron": "0",
  "product_created_datetime": "2022-06-23 14:47:53",
  "product_currency": null,
  "product_reward_entitled": "true",
  "product_country": "1",
  "product_type": "seamless",
  "product_down_time": null,
  "product_down_timed_at": null,
  "product_up_time": null,
  "product_up_timed_at": null,
  "product_down_by": null,
  "product_up_by": null,
  "product_maintenance_scheduled": "0",
  "product_maintenance_scheduled_from": null,
  "product_maintenance_scheduled_to": null,
  "member_product_id": "50231",
  "member_id": "21",
  "member_product_created_datetime": "2022-09-20 22:29:29",
  "member_product_username": "oaxGMI16N3CRLQ7CR",
  "member_product_password": "oaxGMI16N3CRLQ7CR",
  "member_product_lastlogin_datetime": "2022-11-20 21:06:11",
  "member_product_total_balance": "0.00",
  "member_product_wallet": "0.00",
  "member_product_coin": "0.00",
  "member_product_return_username": "oaxGMI16N3CRLQ7CR",
  "member_product_last_check": "2022-09-20 22:29:29",
  "member_product_status": "inactive",
  "member_product_lock": "true",
  "member_product_in": "false",
  "member_product_nickname": null,
  "lastpull_datetime": null,
  "member_product_bonus": "0.00",
  "member_product_check": "0",
  "member_product_credit_gamein_deduct": null,
  "member_product_promo_gamein_deduct": null,
  "member_product_game_start_datetime": null,
  "member_product_game_end_datetime": null,
  "auth_session": null,
  "auth_expiry": null,
  "member_product_bet_limit": null,
  "member_product_block": "false"
} 
*/

  String? product_id;
  String? product_name;
  String? product_status;
  String? product_category_group;
  String? product_category;
  String? product_desc;
  String? product_grouping;
  String? product_image_url;
  String? product_coin_entitled;
  String? product_provider;
  String? product_percentage;
  String? product_image_url_grey;
  String? product_avenger_direct;
  String? product_main_commission_percentage;
  String? product_upline_commission_percentage;
  String? product_self_commission_percentage;
  String? product_test;
  String? product_sequence;
  String? ping_with_cron;
  String? product_created_datetime;
  String? product_currency;
  String? product_reward_entitled;
  String? product_country;
  String? product_type;
  String? product_down_time;
  String? product_down_timed_at;
  String? product_up_time;
  String? product_up_timed_at;
  String? product_down_by;
  String? product_up_by;
  String? product_maintenance_scheduled;
  String? product_maintenance_scheduled_from;
  String? product_maintenance_scheduled_to;
  String? member_product_id;
  String? member_id;
  String? member_product_created_datetime;
  String? member_product_username;
  String? member_product_password;
  String? member_product_lastlogin_datetime;
  String? member_product_total_balance;
  String? member_product_wallet;
  String? member_product_coin;
  String? member_product_return_username;
  String? member_product_last_check;
  String? member_product_status;
  String? member_product_lock;
  String? member_product_in;
  String? member_product_nickname;
  String? lastpull_datetime;
  String? member_product_bonus;
  String? member_product_check;
  String? member_product_credit_gamein_deduct;
  String? member_product_promo_gamein_deduct;
  String? member_product_game_start_datetime;
  String? member_product_game_end_datetime;
  String? auth_session;
  String? auth_expiry;
  String? member_product_bet_limit;
  String? member_product_block;

  AvailableCreditsResponseProductDetail({
    this.product_id,
    this.product_name,
    this.product_status,
    this.product_category_group,
    this.product_category,
    this.product_desc,
    this.product_grouping,
    this.product_image_url,
    this.product_coin_entitled,
    this.product_provider,
    this.product_percentage,
    this.product_image_url_grey,
    this.product_avenger_direct,
    this.product_main_commission_percentage,
    this.product_upline_commission_percentage,
    this.product_self_commission_percentage,
    this.product_test,
    this.product_sequence,
    this.ping_with_cron,
    this.product_created_datetime,
    this.product_currency,
    this.product_reward_entitled,
    this.product_country,
    this.product_type,
    this.product_down_time,
    this.product_down_timed_at,
    this.product_up_time,
    this.product_up_timed_at,
    this.product_down_by,
    this.product_up_by,
    this.product_maintenance_scheduled,
    this.product_maintenance_scheduled_from,
    this.product_maintenance_scheduled_to,
    this.member_product_id,
    this.member_id,
    this.member_product_created_datetime,
    this.member_product_username,
    this.member_product_password,
    this.member_product_lastlogin_datetime,
    this.member_product_total_balance,
    this.member_product_wallet,
    this.member_product_coin,
    this.member_product_return_username,
    this.member_product_last_check,
    this.member_product_status,
    this.member_product_lock,
    this.member_product_in,
    this.member_product_nickname,
    this.lastpull_datetime,
    this.member_product_bonus,
    this.member_product_check,
    this.member_product_credit_gamein_deduct,
    this.member_product_promo_gamein_deduct,
    this.member_product_game_start_datetime,
    this.member_product_game_end_datetime,
    this.auth_session,
    this.auth_expiry,
    this.member_product_bet_limit,
    this.member_product_block,
  });
  AvailableCreditsResponseProductDetail.fromJson(Map<String, dynamic> json) {
    product_id = json['product_id']?.toString();
    product_name = json['product_name']?.toString();
    product_status = json['product_status']?.toString();
    product_category_group = json['product_category_group']?.toString();
    product_category = json['product_category']?.toString();
    product_desc = json['product_desc']?.toString();
    product_grouping = json['product_grouping']?.toString();
    product_image_url = json['product_image_url']?.toString();
    product_coin_entitled = json['product_coin_entitled']?.toString();
    product_provider = json['product_provider']?.toString();
    product_percentage = json['product_percentage']?.toString();
    product_image_url_grey = json['product_image_url_grey']?.toString();
    product_avenger_direct = json['product_avenger_direct']?.toString();
    product_main_commission_percentage =
        json['product_main_commission_percentage']?.toString();
    product_upline_commission_percentage =
        json['product_upline_commission_percentage']?.toString();
    product_self_commission_percentage =
        json['product_self_commission_percentage']?.toString();
    product_test = json['product_test']?.toString();
    product_sequence = json['product_sequence']?.toString();
    ping_with_cron = json['ping_with_cron']?.toString();
    product_created_datetime = json['product_created_datetime']?.toString();
    product_currency = json['product_currency']?.toString();
    product_reward_entitled = json['product_reward_entitled']?.toString();
    product_country = json['product_country']?.toString();
    product_type = json['product_type']?.toString();
    product_down_time = json['product_down_time']?.toString();
    product_down_timed_at = json['product_down_timed_at']?.toString();
    product_up_time = json['product_up_time']?.toString();
    product_up_timed_at = json['product_up_timed_at']?.toString();
    product_down_by = json['product_down_by']?.toString();
    product_up_by = json['product_up_by']?.toString();
    product_maintenance_scheduled =
        json['product_maintenance_scheduled']?.toString();
    product_maintenance_scheduled_from =
        json['product_maintenance_scheduled_from']?.toString();
    product_maintenance_scheduled_to =
        json['product_maintenance_scheduled_to']?.toString();
    member_product_id = json['member_product_id']?.toString();
    member_id = json['member_id']?.toString();
    member_product_created_datetime =
        json['member_product_created_datetime']?.toString();
    member_product_username = json['member_product_username']?.toString();
    member_product_password = json['member_product_password']?.toString();
    member_product_lastlogin_datetime =
        json['member_product_lastlogin_datetime']?.toString();
    member_product_total_balance =
        json['member_product_total_balance']?.toString();
    member_product_wallet = json['member_product_wallet']?.toString();
    member_product_coin = json['member_product_coin']?.toString();
    member_product_return_username =
        json['member_product_return_username']?.toString();
    member_product_last_check = json['member_product_last_check']?.toString();
    member_product_status = json['member_product_status']?.toString();
    member_product_lock = json['member_product_lock']?.toString();
    member_product_in = json['member_product_in']?.toString();
    member_product_nickname = json['member_product_nickname']?.toString();
    lastpull_datetime = json['lastpull_datetime']?.toString();
    member_product_bonus = json['member_product_bonus']?.toString();
    member_product_check = json['member_product_check']?.toString();
    member_product_credit_gamein_deduct =
        json['member_product_credit_gamein_deduct']?.toString();
    member_product_promo_gamein_deduct =
        json['member_product_promo_gamein_deduct']?.toString();
    member_product_game_start_datetime =
        json['member_product_game_start_datetime']?.toString();
    member_product_game_end_datetime =
        json['member_product_game_end_datetime']?.toString();
    auth_session = json['auth_session']?.toString();
    auth_expiry = json['auth_expiry']?.toString();
    member_product_bet_limit = json['member_product_bet_limit']?.toString();
    member_product_block = json['member_product_block']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['product_id'] = product_id;
    data['product_name'] = product_name;
    data['product_status'] = product_status;
    data['product_category_group'] = product_category_group;
    data['product_category'] = product_category;
    data['product_desc'] = product_desc;
    data['product_grouping'] = product_grouping;
    data['product_image_url'] = product_image_url;
    data['product_coin_entitled'] = product_coin_entitled;
    data['product_provider'] = product_provider;
    data['product_percentage'] = product_percentage;
    data['product_image_url_grey'] = product_image_url_grey;
    data['product_avenger_direct'] = product_avenger_direct;
    data['product_main_commission_percentage'] =
        product_main_commission_percentage;
    data['product_upline_commission_percentage'] =
        product_upline_commission_percentage;
    data['product_self_commission_percentage'] =
        product_self_commission_percentage;
    data['product_test'] = product_test;
    data['product_sequence'] = product_sequence;
    data['ping_with_cron'] = ping_with_cron;
    data['product_created_datetime'] = product_created_datetime;
    data['product_currency'] = product_currency;
    data['product_reward_entitled'] = product_reward_entitled;
    data['product_country'] = product_country;
    data['product_type'] = product_type;
    data['product_down_time'] = product_down_time;
    data['product_down_timed_at'] = product_down_timed_at;
    data['product_up_time'] = product_up_time;
    data['product_up_timed_at'] = product_up_timed_at;
    data['product_down_by'] = product_down_by;
    data['product_up_by'] = product_up_by;
    data['product_maintenance_scheduled'] = product_maintenance_scheduled;
    data['product_maintenance_scheduled_from'] =
        product_maintenance_scheduled_from;
    data['product_maintenance_scheduled_to'] = product_maintenance_scheduled_to;
    data['member_product_id'] = member_product_id;
    data['member_id'] = member_id;
    data['member_product_created_datetime'] = member_product_created_datetime;
    data['member_product_username'] = member_product_username;
    data['member_product_password'] = member_product_password;
    data['member_product_lastlogin_datetime'] =
        member_product_lastlogin_datetime;
    data['member_product_total_balance'] = member_product_total_balance;
    data['member_product_wallet'] = member_product_wallet;
    data['member_product_coin'] = member_product_coin;
    data['member_product_return_username'] = member_product_return_username;
    data['member_product_last_check'] = member_product_last_check;
    data['member_product_status'] = member_product_status;
    data['member_product_lock'] = member_product_lock;
    data['member_product_in'] = member_product_in;
    data['member_product_nickname'] = member_product_nickname;
    data['lastpull_datetime'] = lastpull_datetime;
    data['member_product_bonus'] = member_product_bonus;
    data['member_product_check'] = member_product_check;
    data['member_product_credit_gamein_deduct'] =
        member_product_credit_gamein_deduct;
    data['member_product_promo_gamein_deduct'] =
        member_product_promo_gamein_deduct;
    data['member_product_game_start_datetime'] =
        member_product_game_start_datetime;
    data['member_product_game_end_datetime'] = member_product_game_end_datetime;
    data['auth_session'] = auth_session;
    data['auth_expiry'] = auth_expiry;
    data['member_product_bet_limit'] = member_product_bet_limit;
    data['member_product_block'] = member_product_block;
    return data;
  }
}

class AvailableCreditsResponse {
/*
{
  "avaiableTransfer": "5009.13",
  "coinAvailable": "5.50",
  "coinEntitle": "false",
  "ptsCopyWriting": "1.00:1.00 PTS",
  "selfCommission": "0.50%",
  "username": "oaxGMI16N3CRLQ7CR",
  "password": "oaxGMI16N3CRLQ7CR",
  "productDetail": {
    "product_id": "99",
    "product_name": "THREESING",
    "product_status": "active",
    "product_category_group": "Sport",
    "product_category": "SPORT",
    "product_desc": "THREESING",
    "product_grouping": null,
    "product_image_url": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/3sing.jpg",
    "product_coin_entitled": "false",
    "product_provider": "THREESING",
    "product_percentage": "10.00",
    "product_image_url_grey": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/Bnw/3sing-bnw.jpg",
    "product_avenger_direct": "false",
    "product_main_commission_percentage": "0.20",
    "product_upline_commission_percentage": "0.30",
    "product_self_commission_percentage": "0.50",
    "product_test": "true",
    "product_sequence": "43",
    "ping_with_cron": "0",
    "product_created_datetime": "2022-06-23 14:47:53",
    "product_currency": null,
    "product_reward_entitled": "true",
    "product_country": "1",
    "product_type": "seamless",
    "product_down_time": null,
    "product_down_timed_at": null,
    "product_up_time": null,
    "product_up_timed_at": null,
    "product_down_by": null,
    "product_up_by": null,
    "product_maintenance_scheduled": "0",
    "product_maintenance_scheduled_from": null,
    "product_maintenance_scheduled_to": null,
    "member_product_id": "50231",
    "member_id": "21",
    "member_product_created_datetime": "2022-09-20 22:29:29",
    "member_product_username": "oaxGMI16N3CRLQ7CR",
    "member_product_password": "oaxGMI16N3CRLQ7CR",
    "member_product_lastlogin_datetime": "2022-11-20 21:06:11",
    "member_product_total_balance": "0.00",
    "member_product_wallet": "0.00",
    "member_product_coin": "0.00",
    "member_product_return_username": "oaxGMI16N3CRLQ7CR",
    "member_product_last_check": "2022-09-20 22:29:29",
    "member_product_status": "inactive",
    "member_product_lock": "true",
    "member_product_in": "false",
    "member_product_nickname": null,
    "lastpull_datetime": null,
    "member_product_bonus": "0.00",
    "member_product_check": "0",
    "member_product_credit_gamein_deduct": null,
    "member_product_promo_gamein_deduct": null,
    "member_product_game_start_datetime": null,
    "member_product_game_end_datetime": null,
    "auth_session": null,
    "auth_expiry": null,
    "member_product_bet_limit": null,
    "member_product_block": "false"
  },
  "inGameStatus": "",
  "type": "web",
  "todayStake": 0,
  "yesterdayStake": 0,
  "hasViewOptions": true
} 
*/

  String? avaiableTransfer;
  String? coinAvailable;
  String? coinEntitle;
  String? ptsCopyWriting;
  String? selfCommission;
  String? username;
  String? password;
  AvailableCreditsResponseProductDetail? productDetail;
  String? inGameStatus;
  String? type;
  int? todayStake;
  int? yesterdayStake;
  bool? hasViewOptions;

  AvailableCreditsResponse({
    this.avaiableTransfer,
    this.coinAvailable,
    this.coinEntitle,
    this.ptsCopyWriting,
    this.selfCommission,
    this.username,
    this.password,
    this.productDetail,
    this.inGameStatus,
    this.type,
    this.todayStake,
    this.yesterdayStake,
    this.hasViewOptions,
  });
  AvailableCreditsResponse.fromJson(Map<String, dynamic> json) {
    avaiableTransfer = json['avaiableTransfer']?.toString();
    coinAvailable = json['coinAvailable']?.toString();
    coinEntitle = json['coinEntitle']?.toString();
    ptsCopyWriting = json['ptsCopyWriting']?.toString();
    selfCommission = json['selfCommission']?.toString();
    username = json['username']?.toString();
    password = json['password']?.toString();
    productDetail = (json['productDetail'] != null)
        ? AvailableCreditsResponseProductDetail.fromJson(json['productDetail'])
        : null;
    inGameStatus = json['inGameStatus']?.toString();
    type = json['type']?.toString();
    todayStake = json['todayStake']?.toInt();
    yesterdayStake = json['yesterdayStake']?.toInt();
    hasViewOptions = json['hasViewOptions'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['avaiableTransfer'] = avaiableTransfer;
    data['coinAvailable'] = coinAvailable;
    data['coinEntitle'] = coinEntitle;
    data['ptsCopyWriting'] = ptsCopyWriting;
    data['selfCommission'] = selfCommission;
    data['username'] = username;
    data['password'] = password;
    if (productDetail != null) {
      data['productDetail'] = productDetail!.toJson();
    }
    data['inGameStatus'] = inGameStatus;
    data['type'] = type;
    data['todayStake'] = todayStake;
    data['yesterdayStake'] = yesterdayStake;
    data['hasViewOptions'] = hasViewOptions;
    return data;
  }
}

class AvailableCredits {
/*
{
  "msg": "Get Available Crrdit Success",
  "response": {
    "avaiableTransfer": "5009.13",
    "coinAvailable": "5.50",
    "coinEntitle": "false",
    "ptsCopyWriting": "1.00:1.00 PTS",
    "selfCommission": "0.50%",
    "username": "oaxGMI16N3CRLQ7CR",
    "password": "oaxGMI16N3CRLQ7CR",
    "productDetail": {
      "product_id": "99",
      "product_name": "THREESING",
      "product_status": "active",
      "product_category_group": "Sport",
      "product_category": "SPORT",
      "product_desc": "THREESING",
      "product_grouping": null,
      "product_image_url": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/3sing.jpg",
      "product_coin_entitled": "false",
      "product_provider": "THREESING",
      "product_percentage": "10.00",
      "product_image_url_grey": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/Bnw/3sing-bnw.jpg",
      "product_avenger_direct": "false",
      "product_main_commission_percentage": "0.20",
      "product_upline_commission_percentage": "0.30",
      "product_self_commission_percentage": "0.50",
      "product_test": "true",
      "product_sequence": "43",
      "ping_with_cron": "0",
      "product_created_datetime": "2022-06-23 14:47:53",
      "product_currency": null,
      "product_reward_entitled": "true",
      "product_country": "1",
      "product_type": "seamless",
      "product_down_time": null,
      "product_down_timed_at": null,
      "product_up_time": null,
      "product_up_timed_at": null,
      "product_down_by": null,
      "product_up_by": null,
      "product_maintenance_scheduled": "0",
      "product_maintenance_scheduled_from": null,
      "product_maintenance_scheduled_to": null,
      "member_product_id": "50231",
      "member_id": "21",
      "member_product_created_datetime": "2022-09-20 22:29:29",
      "member_product_username": "oaxGMI16N3CRLQ7CR",
      "member_product_password": "oaxGMI16N3CRLQ7CR",
      "member_product_lastlogin_datetime": "2022-11-20 21:06:11",
      "member_product_total_balance": "0.00",
      "member_product_wallet": "0.00",
      "member_product_coin": "0.00",
      "member_product_return_username": "oaxGMI16N3CRLQ7CR",
      "member_product_last_check": "2022-09-20 22:29:29",
      "member_product_status": "inactive",
      "member_product_lock": "true",
      "member_product_in": "false",
      "member_product_nickname": null,
      "lastpull_datetime": null,
      "member_product_bonus": "0.00",
      "member_product_check": "0",
      "member_product_credit_gamein_deduct": null,
      "member_product_promo_gamein_deduct": null,
      "member_product_game_start_datetime": null,
      "member_product_game_end_datetime": null,
      "auth_session": null,
      "auth_expiry": null,
      "member_product_bet_limit": null,
      "member_product_block": "false"
    },
    "inGameStatus": "",
    "type": "web",
    "todayStake": 0,
    "yesterdayStake": 0,
    "hasViewOptions": true
  }
} 
*/

  String? msg;
  AvailableCreditsResponse? response;

  AvailableCredits({
    this.msg,
    this.response,
  });
  AvailableCredits.fromJson(Map<String, dynamic> json) {
    msg = json['msg']?.toString();
    response = (json['response'] != null)
        ? AvailableCreditsResponse.fromJson(json['response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['msg'] = msg;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
