///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductsModelResponseProducts {
/*
{
  "product_id": "124",
  "product_name": "OBET",
  "product_status": "active",
  "product_category_group": "Sport",
  "product_category": "SPORT",
  "product_desc": "OBET",
  "product_grouping": null,
  "product_image_url": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/bet33.jpg",
  "product_coin_entitled": "false",
  "product_provider": "OBET",
  "product_percentage": "10.00",
  "product_image_url_grey": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/Bnw/bet33bw.jpg",
  "product_avenger_direct": "false",
  "product_main_commission_percentage": "0.20",
  "product_upline_commission_percentage": "0.30",
  "product_self_commission_percentage": "0.50",
  "product_test": "true",
  "product_sequence": null,
  "ping_with_cron": "0",
  "product_created_datetime": "2022-07-28 14:05:49",
  "product_currency": null,
  "product_reward_entitled": "false",
  "product_country": "2",
  "product_type": "seamless",
  "product_down_time": null,
  "product_down_timed_at": null,
  "product_up_time": null,
  "product_up_timed_at": null,
  "product_down_by": null,
  "product_up_by": null,
  "product_maintenance_scheduled": "0",
  "product_maintenance_scheduled_from": "01/01 07:30",
  "product_maintenance_scheduled_to": "01/01 07:30",
  "inGameStatus": "",
  "termStatus": true,
  "termText": "Any irregular betting cancelled by the game company,our platform represent a third party payment will be no explanation given."
} 
*/

  String? productId;
  String? productName;
  String? productStatus;
  String? productCategoryGroup;
  String? productCategory;
  String? productDesc;
  String? productGrouping;
  String? productImageUrl;
  String? productCoinEntitled;
  String? productProvider;
  String? productPercentage;
  String? productImageUrlGrey;
  String? productAvengerDirect;
  String? productMainCommissionPercentage;
  String? productUplineCommissionPercentage;
  String? productSelfCommissionPercentage;
  String? productTest;
  String? productSequence;
  String? pingWithCron;
  String? productCreatedDatetime;
  String? productCurrency;
  String? productRewardEntitled;
  String? productCountry;
  String? productType;
  String? productDownTime;
  String? productDownTimedAt;
  String? productUpTime;
  String? productUpTimedAt;
  String? productDownBy;
  String? productUpBy;
  String? productMaintenanceScheduled;
  String? productMaintenanceScheduledFrom;
  String? productMaintenanceScheduledTo;
  String? inGameStatus;
  bool? termStatus;
  String? termText;

  ProductsModelResponseProducts({
    this.productId,
    this.productName,
    this.productStatus,
    this.productCategoryGroup,
    this.productCategory,
    this.productDesc,
    this.productGrouping,
    this.productImageUrl,
    this.productCoinEntitled,
    this.productProvider,
    this.productPercentage,
    this.productImageUrlGrey,
    this.productAvengerDirect,
    this.productMainCommissionPercentage,
    this.productUplineCommissionPercentage,
    this.productSelfCommissionPercentage,
    this.productTest,
    this.productSequence,
    this.pingWithCron,
    this.productCreatedDatetime,
    this.productCurrency,
    this.productRewardEntitled,
    this.productCountry,
    this.productType,
    this.productDownTime,
    this.productDownTimedAt,
    this.productUpTime,
    this.productUpTimedAt,
    this.productDownBy,
    this.productUpBy,
    this.productMaintenanceScheduled,
    this.productMaintenanceScheduledFrom,
    this.productMaintenanceScheduledTo,
    this.inGameStatus,
    this.termStatus,
    this.termText,
  });
  ProductsModelResponseProducts.fromJson(Map<String, dynamic> json) {
    productId = json['product_id']?.toString();
    productName = json['product_name']?.toString();
    productStatus = json['product_status']?.toString();
    productCategoryGroup = json['product_category_group']?.toString();
    productCategory = json['product_category']?.toString();
    productDesc = json['product_desc']?.toString();
    productGrouping = json['product_grouping']?.toString();
    productImageUrl = json['product_image_url']?.toString();
    productCoinEntitled = json['product_coin_entitled']?.toString();
    productProvider = json['product_provider']?.toString();
    productPercentage = json['product_percentage']?.toString();
    productImageUrlGrey = json['product_image_url_grey']?.toString();
    productAvengerDirect = json['product_avenger_direct']?.toString();
    productMainCommissionPercentage =
        json['product_main_commission_percentage']?.toString();
    productUplineCommissionPercentage =
        json['product_upline_commission_percentage']?.toString();
    productSelfCommissionPercentage =
        json['product_self_commission_percentage']?.toString();
    productTest = json['product_test']?.toString();
    productSequence = json['product_sequence']?.toString();
    pingWithCron = json['ping_with_cron']?.toString();
    productCreatedDatetime = json['product_created_datetime']?.toString();
    productCurrency = json['product_currency']?.toString();
    productRewardEntitled = json['product_reward_entitled']?.toString();
    productCountry = json['product_country']?.toString();
    productType = json['product_type']?.toString();
    productDownTime = json['product_down_time']?.toString();
    productDownTimedAt = json['product_down_timed_at']?.toString();
    productUpTime = json['product_up_time']?.toString();
    productUpTimedAt = json['product_up_timed_at']?.toString();
    productDownBy = json['product_down_by']?.toString();
    productUpBy = json['product_up_by']?.toString();
    productMaintenanceScheduled =
        json['product_maintenance_scheduled']?.toString();
    productMaintenanceScheduledFrom =
        json['product_maintenance_scheduled_from']?.toString();
    productMaintenanceScheduledTo =
        json['product_maintenance_scheduled_to']?.toString();
    inGameStatus = json['inGameStatus']?.toString();
    termStatus = json['termStatus'];
    termText = json['termText']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['product_id'] = productId;
    data['product_name'] = productName;
    data['product_status'] = productStatus;
    data['product_category_group'] = productCategoryGroup;
    data['product_category'] = productCategory;
    data['product_desc'] = productDesc;
    data['product_grouping'] = productGrouping;
    data['product_image_url'] = productImageUrl;
    data['product_coin_entitled'] = productCoinEntitled;
    data['product_provider'] = productProvider;
    data['product_percentage'] = productPercentage;
    data['product_image_url_grey'] = productImageUrlGrey;
    data['product_avenger_direct'] = productAvengerDirect;
    data['product_main_commission_percentage'] =
        productMainCommissionPercentage;
    data['product_upline_commission_percentage'] =
        productUplineCommissionPercentage;
    data['product_self_commission_percentage'] =
        productSelfCommissionPercentage;
    data['product_test'] = productTest;
    data['product_sequence'] = productSequence;
    data['ping_with_cron'] = pingWithCron;
    data['product_created_datetime'] = productCreatedDatetime;
    data['product_currency'] = productCurrency;
    data['product_reward_entitled'] = productRewardEntitled;
    data['product_country'] = productCountry;
    data['product_type'] = productType;
    data['product_down_time'] = productDownTime;
    data['product_down_timed_at'] = productDownTimedAt;
    data['product_up_time'] = productUpTime;
    data['product_up_timed_at'] = productUpTimedAt;
    data['product_down_by'] = productDownBy;
    data['product_up_by'] = productUpBy;
    data['product_maintenance_scheduled'] = productMaintenanceScheduled;
    data['product_maintenance_scheduled_from'] =
        productMaintenanceScheduledFrom;
    data['product_maintenance_scheduled_to'] = productMaintenanceScheduledTo;
    data['inGameStatus'] = inGameStatus;
    data['termStatus'] = termStatus;
    data['termText'] = termText;
    return data;
  }
}

class ProductsModelResponse {
/*
{
  "products": [
    {
      "product_id": "124",
      "product_name": "OBET",
      "product_status": "active",
      "product_category_group": "Sport",
      "product_category": "SPORT",
      "product_desc": "OBET",
      "product_grouping": null,
      "product_image_url": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/bet33.jpg",
      "product_coin_entitled": "false",
      "product_provider": "OBET",
      "product_percentage": "10.00",
      "product_image_url_grey": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/Bnw/bet33bw.jpg",
      "product_avenger_direct": "false",
      "product_main_commission_percentage": "0.20",
      "product_upline_commission_percentage": "0.30",
      "product_self_commission_percentage": "0.50",
      "product_test": "true",
      "product_sequence": null,
      "ping_with_cron": "0",
      "product_created_datetime": "2022-07-28 14:05:49",
      "product_currency": null,
      "product_reward_entitled": "false",
      "product_country": "2",
      "product_type": "seamless",
      "product_down_time": null,
      "product_down_timed_at": null,
      "product_up_time": null,
      "product_up_timed_at": null,
      "product_down_by": null,
      "product_up_by": null,
      "product_maintenance_scheduled": "0",
      "product_maintenance_scheduled_from": "01/01 07:30",
      "product_maintenance_scheduled_to": "01/01 07:30",
      "inGameStatus": "",
      "termStatus": true,
      "termText": "Any irregular betting cancelled by the game company,our platform represent a third party payment will be no explanation given."
    }
  ],
  "walletBalance": "0.00",
  "coinBalance": "24.00",
  "interestBalance": "0.00"
} 
*/

  List<ProductsModelResponseProducts?>? products;
  String? walletBalance;
  String? coinBalance;
  String? interestBalance;

  ProductsModelResponse({
    this.products,
    this.walletBalance,
    this.coinBalance,
    this.interestBalance,
  });
  ProductsModelResponse.fromJson(Map<String, dynamic> json) {
    if (json['products'] != null) {
      final v = json['products'];
      final arr0 = <ProductsModelResponseProducts>[];
      v.forEach((v) {
        arr0.add(ProductsModelResponseProducts.fromJson(v));
      });
      products = arr0;
    }
    walletBalance = json['walletBalance']?.toString();
    coinBalance = json['coinBalance']?.toString();
    interestBalance = json['interestBalance']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (products != null) {
      final v = products;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['products'] = arr0;
    }
    data['walletBalance'] = walletBalance;
    data['coinBalance'] = coinBalance;
    data['interestBalance'] = interestBalance;
    return data;
  }
}

class ProductsModel {
/*
{
  "msg": "Get Product List Success",
  "response": {
    "products": [
      {
        "product_id": "124",
        "product_name": "OBET",
        "product_status": "active",
        "product_category_group": "Sport",
        "product_category": "SPORT",
        "product_desc": "OBET",
        "product_grouping": null,
        "product_image_url": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/bet33.jpg",
        "product_coin_entitled": "false",
        "product_provider": "OBET",
        "product_percentage": "10.00",
        "product_image_url_grey": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/Bnw/bet33bw.jpg",
        "product_avenger_direct": "false",
        "product_main_commission_percentage": "0.20",
        "product_upline_commission_percentage": "0.30",
        "product_self_commission_percentage": "0.50",
        "product_test": "true",
        "product_sequence": null,
        "ping_with_cron": "0",
        "product_created_datetime": "2022-07-28 14:05:49",
        "product_currency": null,
        "product_reward_entitled": "false",
        "product_country": "2",
        "product_type": "seamless",
        "product_down_time": null,
        "product_down_timed_at": null,
        "product_up_time": null,
        "product_up_timed_at": null,
        "product_down_by": null,
        "product_up_by": null,
        "product_maintenance_scheduled": "0",
        "product_maintenance_scheduled_from": "01/01 07:30",
        "product_maintenance_scheduled_to": "01/01 07:30",
        "inGameStatus": "",
        "termStatus": true,
        "termText": "Any irregular betting cancelled by the game company,our platform represent a third party payment will be no explanation given."
      }
    ],
    "walletBalance": "0.00",
    "coinBalance": "24.00",
    "interestBalance": "0.00"
  }
} 
*/

  String? msg;
  ProductsModelResponse? response;

  ProductsModel({
    this.msg,
    this.response,
  });
  ProductsModel.fromJson(Map<String, dynamic> json) {
    msg = json['msg']?.toString();
    response = (json['response'] != null)
        ? ProductsModelResponse.fromJson(json['response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['msg'] = msg;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
