///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductsModelResponseProducts {
/*
{
  "product_id": "113",
  "product_name": "OBET",
  "product_status": "active",
  "product_category_group": "体育",
  "product_category": "SPORT",
  "product_desc": "OBET",
  "product_grouping": null,
  "product_image_url": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/bet33.jpg",
  "product_coin_entitled": "false",
  "product_provider": "OBET",
  "product_percentage": "10.00",
  "product_image_url_grey": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/Bnw/bet33bw.jpg",
  "product_avenger_direct": "false",
  "product_main_commission_percentage": "0.20",
  "product_upline_commission_percentage": "0.30",
  "product_self_commission_percentage": "0.50",
  "product_test": "true",
  "product_sequence": null,
  "ping_with_cron": "0",
  "product_created_datetime": "2022-07-28 14:05:49",
  "product_currency": null,
  "product_reward_entitled": "false",
  "product_country": "1",
  "product_type": "seamless",
  "product_down_time": null,
  "product_down_timed_at": null,
  "product_up_time": null,
  "product_up_timed_at": null,
  "product_down_by": null,
  "product_up_by": null,
  "product_maintenance_scheduled": "0",
  "product_maintenance_scheduled_from": "01/01 07:30",
  "product_maintenance_scheduled_to": "01/01 07:30",
  "inGameStatus": "",
  "termStatus": true,
  "termText": "任何被游戏公司取消的不正规单据，平台属于第三方支付，无需给予任何解释"
} 
*/

  String? product_id;
  String? product_name;
  String? product_status;
  String? product_category_group;
  String? product_category;
  String? product_desc;
  String? product_grouping;
  String? product_image_url;
  String? product_coin_entitled;
  String? product_provider;
  String? product_percentage;
  String? product_image_url_grey;
  String? product_avenger_direct;
  String? product_main_commission_percentage;
  String? product_upline_commission_percentage;
  String? product_self_commission_percentage;
  String? product_test;
  String? product_sequence;
  String? ping_with_cron;
  String? product_created_datetime;
  String? product_currency;
  String? product_reward_entitled;
  String? product_country;
  String? product_type;
  String? product_down_time;
  String? product_down_timed_at;
  String? product_up_time;
  String? product_up_timed_at;
  String? product_down_by;
  String? product_up_by;
  String? product_maintenance_scheduled;
  String? product_maintenance_scheduled_from;
  String? product_maintenance_scheduled_to;
  String? inGameStatus;
  bool? termStatus;
  String? termText;

  ProductsModelResponseProducts({
    this.product_id,
    this.product_name,
    this.product_status,
    this.product_category_group,
    this.product_category,
    this.product_desc,
    this.product_grouping,
    this.product_image_url,
    this.product_coin_entitled,
    this.product_provider,
    this.product_percentage,
    this.product_image_url_grey,
    this.product_avenger_direct,
    this.product_main_commission_percentage,
    this.product_upline_commission_percentage,
    this.product_self_commission_percentage,
    this.product_test,
    this.product_sequence,
    this.ping_with_cron,
    this.product_created_datetime,
    this.product_currency,
    this.product_reward_entitled,
    this.product_country,
    this.product_type,
    this.product_down_time,
    this.product_down_timed_at,
    this.product_up_time,
    this.product_up_timed_at,
    this.product_down_by,
    this.product_up_by,
    this.product_maintenance_scheduled,
    this.product_maintenance_scheduled_from,
    this.product_maintenance_scheduled_to,
    this.inGameStatus,
    this.termStatus,
    this.termText,
  });
  ProductsModelResponseProducts.fromJson(Map<String, dynamic> json) {
    product_id = json['product_id']?.toString();
    product_name = json['product_name']?.toString();
    product_status = json['product_status']?.toString();
    product_category_group = json['product_category_group']?.toString();
    product_category = json['product_category']?.toString();
    product_desc = json['product_desc']?.toString();
    product_grouping = json['product_grouping']?.toString();
    product_image_url = json['product_image_url']?.toString();
    product_coin_entitled = json['product_coin_entitled']?.toString();
    product_provider = json['product_provider']?.toString();
    product_percentage = json['product_percentage']?.toString();
    product_image_url_grey = json['product_image_url_grey']?.toString();
    product_avenger_direct = json['product_avenger_direct']?.toString();
    product_main_commission_percentage =
        json['product_main_commission_percentage']?.toString();
    product_upline_commission_percentage =
        json['product_upline_commission_percentage']?.toString();
    product_self_commission_percentage =
        json['product_self_commission_percentage']?.toString();
    product_test = json['product_test']?.toString();
    product_sequence = json['product_sequence']?.toString();
    ping_with_cron = json['ping_with_cron']?.toString();
    product_created_datetime = json['product_created_datetime']?.toString();
    product_currency = json['product_currency']?.toString();
    product_reward_entitled = json['product_reward_entitled']?.toString();
    product_country = json['product_country']?.toString();
    product_type = json['product_type']?.toString();
    product_down_time = json['product_down_time']?.toString();
    product_down_timed_at = json['product_down_timed_at']?.toString();
    product_up_time = json['product_up_time']?.toString();
    product_up_timed_at = json['product_up_timed_at']?.toString();
    product_down_by = json['product_down_by']?.toString();
    product_up_by = json['product_up_by']?.toString();
    product_maintenance_scheduled =
        json['product_maintenance_scheduled']?.toString();
    product_maintenance_scheduled_from =
        json['product_maintenance_scheduled_from']?.toString();
    product_maintenance_scheduled_to =
        json['product_maintenance_scheduled_to']?.toString();
    inGameStatus = json['inGameStatus']?.toString();
    termStatus = json['termStatus'];
    termText = json['termText']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['product_id'] = product_id;
    data['product_name'] = product_name;
    data['product_status'] = product_status;
    data['product_category_group'] = product_category_group;
    data['product_category'] = product_category;
    data['product_desc'] = product_desc;
    data['product_grouping'] = product_grouping;
    data['product_image_url'] = product_image_url;
    data['product_coin_entitled'] = product_coin_entitled;
    data['product_provider'] = product_provider;
    data['product_percentage'] = product_percentage;
    data['product_image_url_grey'] = product_image_url_grey;
    data['product_avenger_direct'] = product_avenger_direct;
    data['product_main_commission_percentage'] =
        product_main_commission_percentage;
    data['product_upline_commission_percentage'] =
        product_upline_commission_percentage;
    data['product_self_commission_percentage'] =
        product_self_commission_percentage;
    data['product_test'] = product_test;
    data['product_sequence'] = product_sequence;
    data['ping_with_cron'] = ping_with_cron;
    data['product_created_datetime'] = product_created_datetime;
    data['product_currency'] = product_currency;
    data['product_reward_entitled'] = product_reward_entitled;
    data['product_country'] = product_country;
    data['product_type'] = product_type;
    data['product_down_time'] = product_down_time;
    data['product_down_timed_at'] = product_down_timed_at;
    data['product_up_time'] = product_up_time;
    data['product_up_timed_at'] = product_up_timed_at;
    data['product_down_by'] = product_down_by;
    data['product_up_by'] = product_up_by;
    data['product_maintenance_scheduled'] = product_maintenance_scheduled;
    data['product_maintenance_scheduled_from'] =
        product_maintenance_scheduled_from;
    data['product_maintenance_scheduled_to'] = product_maintenance_scheduled_to;
    data['inGameStatus'] = inGameStatus;
    data['termStatus'] = termStatus;
    data['termText'] = termText;
    return data;
  }
}

class ProductsModelResponse {
/*
{
  "products": [
    {
      "product_id": "113",
      "product_name": "OBET",
      "product_status": "active",
      "product_category_group": "体育",
      "product_category": "SPORT",
      "product_desc": "OBET",
      "product_grouping": null,
      "product_image_url": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/bet33.jpg",
      "product_coin_entitled": "false",
      "product_provider": "OBET",
      "product_percentage": "10.00",
      "product_image_url_grey": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/Bnw/bet33bw.jpg",
      "product_avenger_direct": "false",
      "product_main_commission_percentage": "0.20",
      "product_upline_commission_percentage": "0.30",
      "product_self_commission_percentage": "0.50",
      "product_test": "true",
      "product_sequence": null,
      "ping_with_cron": "0",
      "product_created_datetime": "2022-07-28 14:05:49",
      "product_currency": null,
      "product_reward_entitled": "false",
      "product_country": "1",
      "product_type": "seamless",
      "product_down_time": null,
      "product_down_timed_at": null,
      "product_up_time": null,
      "product_up_timed_at": null,
      "product_down_by": null,
      "product_up_by": null,
      "product_maintenance_scheduled": "0",
      "product_maintenance_scheduled_from": "01/01 07:30",
      "product_maintenance_scheduled_to": "01/01 07:30",
      "inGameStatus": "",
      "termStatus": true,
      "termText": "任何被游戏公司取消的不正规单据，平台属于第三方支付，无需给予任何解释"
    }
  ],
  "walletBalance": "5009.13",
  "coinBalance": "5.50",
  "interestBalance": "0.00"
} 
*/

  List<ProductsModelResponseProducts?>? products;
  String? walletBalance;
  String? coinBalance;
  String? interestBalance;

  ProductsModelResponse({
    this.products,
    this.walletBalance,
    this.coinBalance,
    this.interestBalance,
  });
  ProductsModelResponse.fromJson(Map<String, dynamic> json) {
    if (json['products'] != null) {
      final v = json['products'];
      final arr0 = <ProductsModelResponseProducts>[];
      v.forEach((v) {
        arr0.add(ProductsModelResponseProducts.fromJson(v));
      });
      products = arr0;
    }
    walletBalance = json['walletBalance']?.toString();
    coinBalance = json['coinBalance']?.toString();
    interestBalance = json['interestBalance']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (products != null) {
      final v = products;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['products'] = arr0;
    }
    data['walletBalance'] = walletBalance;
    data['coinBalance'] = coinBalance;
    data['interestBalance'] = interestBalance;
    return data;
  }
}

class ProductsModel {
/*
{
  "msg": "成功获取产品列表",
  "response": {
    "products": [
      {
        "product_id": "113",
        "product_name": "OBET",
        "product_status": "active",
        "product_category_group": "体育",
        "product_category": "SPORT",
        "product_desc": "OBET",
        "product_grouping": null,
        "product_image_url": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/bet33.jpg",
        "product_coin_entitled": "false",
        "product_provider": "OBET",
        "product_percentage": "10.00",
        "product_image_url_grey": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/Bnw/bet33bw.jpg",
        "product_avenger_direct": "false",
        "product_main_commission_percentage": "0.20",
        "product_upline_commission_percentage": "0.30",
        "product_self_commission_percentage": "0.50",
        "product_test": "true",
        "product_sequence": null,
        "ping_with_cron": "0",
        "product_created_datetime": "2022-07-28 14:05:49",
        "product_currency": null,
        "product_reward_entitled": "false",
        "product_country": "1",
        "product_type": "seamless",
        "product_down_time": null,
        "product_down_timed_at": null,
        "product_up_time": null,
        "product_up_timed_at": null,
        "product_down_by": null,
        "product_up_by": null,
        "product_maintenance_scheduled": "0",
        "product_maintenance_scheduled_from": "01/01 07:30",
        "product_maintenance_scheduled_to": "01/01 07:30",
        "inGameStatus": "",
        "termStatus": true,
        "termText": "任何被游戏公司取消的不正规单据，平台属于第三方支付，无需给予任何解释"
      }
    ],
    "walletBalance": "5009.13",
    "coinBalance": "5.50",
    "interestBalance": "0.00"
  }
} 
*/

  String? msg;
  ProductsModelResponse? response;

  ProductsModel({
    this.msg,
    this.response,
  });
  ProductsModel.fromJson(Map<String, dynamic> json) {
    msg = json['msg']?.toString();
    response = (json['response'] != null)
        ? ProductsModelResponse.fromJson(json['response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['msg'] = msg;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
