///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserSessionModelResponseUser {
/*
{
  "id": "21",
  "member_unique_key": "CvrKJgMi16n3crLQ7CRprRKYihf9epbnp29DOcd3tW4FMyNpHYUQX6V7DERpzUY4DDcz8O9pOaR4PxogOGkysdPSNPxJB2gpABtfTkloRsMKxfY8Txklj0OCtHnOUKV0kaBmNBaZNsW3eOtUNelSM3rQ6zOLoxcsgAAaqRskdqygk5lIBRrsVbuBRcHpMIMTAD8aUeNW",
  "password": "68ea8013e0b1da0f9e01f6831a5fcf9a",
  "salt": "5sUTZHtm3AAlX/c4WL5DJzU6IG0kKnFENiWTicLKV3tcLG.5EOj9WQ==",
  "member_username": "Techtest",
  "member_level": "2",
  "ref_upline": "2",
  "member_main_id": "2",
  "member_phone_country": "+60",
  "member_phone": "103600016",
  "member_phone_otp": null,
  "member_phone_otp_salt": null,
  "member_phone_otp_status": "true",
  "last_login": "2022-11-18 21:41:04",
  "user_email": null,
  "registration_token": null,
  "account_status": "active",
  "account_status_remarks": null,
  "created_datetime": "2021-04-30 19:56:17",
  "password_otp": null,
  "password_otp_salt": null,
  "password_expiry": "2022-01-21 02:30:29",
  "bank_account_number": "2",
  "bank_id": "1",
  "shareholder_unique_key": "aHxbKIEsjLXK6jfsr3KNEuxFMuZkTpy9BMNzxyKOLwbVUuDV7DJLX7W9IY2eI6C1Abpw5YJPXiftI4I0DIj7MBUsTdtnKHVjEqdoRDtkSpEik4XdF1ZB1bapwMZINSmzaMH3EFAbUQuxWyto7sXPhp8IKcSpUE80kY2mYMnuuk1bjPnM5ovUfM6y0Ay3YozzDxRXNANJ",
  "bank_account_name": "Affin Bank",
  "pin_status": "true",
  "member_nickname": null,
  "last_login_ip": "162.158.170.141",
  "member_avatar_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/avatar/10.jpg",
  "member_qrcode_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/consumer/avatar/1675683361.png",
  "auth_session": "5fWJhYaSg2qnurPvXM1Y6pr5NOdCvfifsq0eDAdBcR8vUZuZ0eVYGEgulw3JvB2L6xR4FJIsiKAdfD9gvOE6UWJN6xPKufpvO0RmoYKs0hUr6y6C8cGIYS11b9qQOW95GVtQPSULDFyWsQP1yC6M7kLfZWhT8zfr0trQQgfnH0EAKsM3VEDdc6mMPL0BgWQmqEPRvMFM",
  "auth_expiry": "2022-11-19 21:41:04",
  "member_type": "normal",
  "admin_override": "false",
  "admin_override_expiry_datetime": null,
  "member_device_id": "58c549bc790a5ed4",
  "member_device": "android",
  "trace_history": "21-",
  "shareholder_trace_history": "1-",
  "json_trace_history": "[\"21\", \"\"]",
  "member_qrcode_url_new": null,
  "avatar_last_update": "2021-06-16 22:48:09",
  "json_shareholder_trace_history": "[\"1\", \"\"]",
  "fcm_token": "",
  "member_language": "en",
  "member_permission": null,
  "member_referral_url": null,
  "member_directline": "0",
  "member_login_token": null,
  "member_country": "2",
  "vip_level_id": "0",
  "member_country_origin": "1",
  "wallet_pin": "000000",
  "wallet_pin_reset_otp": null,
  "is_transferring": "0",
  "member_topup_bank_id": null,
  "vip_last_update": null,
  "first_time_login": "true",
  "walletBalance": "0.00",
  "coinBalance": "24.00",
  "interestBalance": "0.00",
  "country_id": "2",
  "country_name": "Thailand",
  "country_code": "THB",
  "country_url": "https://suncity.s3.ap-southeast-1.amazonaws.com/country/THB-flag.png",
  "vip_max_withdraw_count": "3",
  "vip_max_withdraw_amount": "200000.00",
  "type": "member",
  "refMemberName": "testtest"
} 
*/

  String? id;
  String? memberUniqueKey;
  String? password;
  String? salt;
  String? memberUsername;
  String? memberLevel;
  String? refUpline;
  String? memberMainId;
  String? memberPhoneCountry;
  String? memberPhone;
  String? memberPhoneOtp;
  String? memberPhoneOtpSalt;
  String? memberPhoneOtpStatus;
  String? lastLogin;
  String? userEmail;
  String? registrationToken;
  String? accountStatus;
  String? accountStatusRemarks;
  String? createdDatetime;
  String? passwordOtp;
  String? passwordOtpSalt;
  String? passwordExpiry;
  String? bankAccountNumber;
  String? bankId;
  String? shareholderUniqueKey;
  String? bankAccountName;
  String? pinStatus;
  String? memberNickname;
  String? lastLoginIp;
  String? memberAvatarUrl;
  String? memberQrcodeUrl;
  String? authSession;
  String? authExpiry;
  String? memberType;
  String? adminOverride;
  String? adminOverrideExpiryDatetime;
  String? memberDeviceId;
  String? memberDevice;
  String? traceHistory;
  String? shareholderTraceHistory;
  String? jsonTraceHistory;
  String? memberQrcodeUrlNew;
  String? avatarLastUpdate;
  String? jsonShareholderTraceHistory;
  String? fcmToken;
  String? memberLanguage;
  String? memberPermission;
  String? memberReferralUrl;
  String? memberDirectline;
  String? memberLoginToken;
  String? memberCountry;
  String? vipLevelId;
  String? memberCountryOrigin;
  String? walletPin;
  String? walletPinResetOtp;
  String? isTransferring;
  String? memberTopupBankId;
  String? vipLastUpdate;
  String? firstTimeLogin;
  String? walletBalance;
  String? coinBalance;
  String? interestBalance;
  String? countryId;
  String? countryName;
  String? countryCode;
  String? countryUrl;
  String? vipMaxWithdrawCount;
  String? vipMaxWithdrawAmount;
  String? type;
  String? refMemberName;

  UserSessionModelResponseUser({
    this.id,
    this.memberUniqueKey,
    this.password,
    this.salt,
    this.memberUsername,
    this.memberLevel,
    this.refUpline,
    this.memberMainId,
    this.memberPhoneCountry,
    this.memberPhone,
    this.memberPhoneOtp,
    this.memberPhoneOtpSalt,
    this.memberPhoneOtpStatus,
    this.lastLogin,
    this.userEmail,
    this.registrationToken,
    this.accountStatus,
    this.accountStatusRemarks,
    this.createdDatetime,
    this.passwordOtp,
    this.passwordOtpSalt,
    this.passwordExpiry,
    this.bankAccountNumber,
    this.bankId,
    this.shareholderUniqueKey,
    this.bankAccountName,
    this.pinStatus,
    this.memberNickname,
    this.lastLoginIp,
    this.memberAvatarUrl,
    this.memberQrcodeUrl,
    this.authSession,
    this.authExpiry,
    this.memberType,
    this.adminOverride,
    this.adminOverrideExpiryDatetime,
    this.memberDeviceId,
    this.memberDevice,
    this.traceHistory,
    this.shareholderTraceHistory,
    this.jsonTraceHistory,
    this.memberQrcodeUrlNew,
    this.avatarLastUpdate,
    this.jsonShareholderTraceHistory,
    this.fcmToken,
    this.memberLanguage,
    this.memberPermission,
    this.memberReferralUrl,
    this.memberDirectline,
    this.memberLoginToken,
    this.memberCountry,
    this.vipLevelId,
    this.memberCountryOrigin,
    this.walletPin,
    this.walletPinResetOtp,
    this.isTransferring,
    this.memberTopupBankId,
    this.vipLastUpdate,
    this.firstTimeLogin,
    this.walletBalance,
    this.coinBalance,
    this.interestBalance,
    this.countryId,
    this.countryName,
    this.countryCode,
    this.countryUrl,
    this.vipMaxWithdrawCount,
    this.vipMaxWithdrawAmount,
    this.type,
    this.refMemberName,
  });
  UserSessionModelResponseUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    memberUniqueKey = json['member_unique_key']?.toString();
    password = json['password']?.toString();
    salt = json['salt']?.toString();
    memberUsername = json['member_username']?.toString();
    memberLevel = json['member_level']?.toString();
    refUpline = json['ref_upline']?.toString();
    memberMainId = json['member_main_id']?.toString();
    memberPhoneCountry = json['member_phone_country']?.toString();
    memberPhone = json['member_phone']?.toString();
    memberPhoneOtp = json['member_phone_otp']?.toString();
    memberPhoneOtpSalt = json['member_phone_otp_salt']?.toString();
    memberPhoneOtpStatus = json['member_phone_otp_status']?.toString();
    lastLogin = json['last_login']?.toString();
    userEmail = json['user_email']?.toString();
    registrationToken = json['registration_token']?.toString();
    accountStatus = json['account_status']?.toString();
    accountStatusRemarks = json['account_status_remarks']?.toString();
    createdDatetime = json['created_datetime']?.toString();
    passwordOtp = json['password_otp']?.toString();
    passwordOtpSalt = json['password_otp_salt']?.toString();
    passwordExpiry = json['password_expiry']?.toString();
    bankAccountNumber = json['bank_account_number']?.toString();
    bankId = json['bank_id']?.toString();
    shareholderUniqueKey = json['shareholder_unique_key']?.toString();
    bankAccountName = json['bank_account_name']?.toString();
    pinStatus = json['pin_status']?.toString();
    memberNickname = json['member_nickname']?.toString();
    lastLoginIp = json['last_login_ip']?.toString();
    memberAvatarUrl = json['member_avatar_url']?.toString();
    memberQrcodeUrl = json['member_qrcode_url']?.toString();
    authSession = json['auth_session']?.toString();
    authExpiry = json['auth_expiry']?.toString();
    memberType = json['member_type']?.toString();
    adminOverride = json['admin_override']?.toString();
    adminOverrideExpiryDatetime =
        json['admin_override_expiry_datetime']?.toString();
    memberDeviceId = json['member_device_id']?.toString();
    memberDevice = json['member_device']?.toString();
    traceHistory = json['trace_history']?.toString();
    shareholderTraceHistory = json['shareholder_trace_history']?.toString();
    jsonTraceHistory = json['json_trace_history']?.toString();
    memberQrcodeUrlNew = json['member_qrcode_url_new']?.toString();
    avatarLastUpdate = json['avatar_last_update']?.toString();
    jsonShareholderTraceHistory =
        json['json_shareholder_trace_history']?.toString();
    fcmToken = json['fcm_token']?.toString();
    memberLanguage = json['member_language']?.toString();
    memberPermission = json['member_permission']?.toString();
    memberReferralUrl = json['member_referral_url']?.toString();
    memberDirectline = json['member_directline']?.toString();
    memberLoginToken = json['member_login_token']?.toString();
    memberCountry = json['member_country']?.toString();
    vipLevelId = json['vip_level_id']?.toString();
    memberCountryOrigin = json['member_country_origin']?.toString();
    walletPin = json['wallet_pin']?.toString();
    walletPinResetOtp = json['wallet_pin_reset_otp']?.toString();
    isTransferring = json['is_transferring']?.toString();
    memberTopupBankId = json['member_topup_bank_id']?.toString();
    vipLastUpdate = json['vip_last_update']?.toString();
    firstTimeLogin = json['first_time_login']?.toString();
    walletBalance = json['walletBalance']?.toString();
    coinBalance = json['coinBalance']?.toString();
    interestBalance = json['interestBalance']?.toString();
    countryId = json['country_id']?.toString();
    countryName = json['country_name']?.toString();
    countryCode = json['country_code']?.toString();
    countryUrl = json['country_url']?.toString();
    vipMaxWithdrawCount = json['vip_max_withdraw_count']?.toString();
    vipMaxWithdrawAmount = json['vip_max_withdraw_amount']?.toString();
    type = json['type']?.toString();
    refMemberName = json['refMemberName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['member_unique_key'] = memberUniqueKey;
    data['password'] = password;
    data['salt'] = salt;
    data['member_username'] = memberUsername;
    data['member_level'] = memberLevel;
    data['ref_upline'] = refUpline;
    data['member_main_id'] = memberMainId;
    data['member_phone_country'] = memberPhoneCountry;
    data['member_phone'] = memberPhone;
    data['member_phone_otp'] = memberPhoneOtp;
    data['member_phone_otp_salt'] = memberPhoneOtpSalt;
    data['member_phone_otp_status'] = memberPhoneOtpStatus;
    data['last_login'] = lastLogin;
    data['user_email'] = userEmail;
    data['registration_token'] = registrationToken;
    data['account_status'] = accountStatus;
    data['account_status_remarks'] = accountStatusRemarks;
    data['created_datetime'] = createdDatetime;
    data['password_otp'] = passwordOtp;
    data['password_otp_salt'] = passwordOtpSalt;
    data['password_expiry'] = passwordExpiry;
    data['bank_account_number'] = bankAccountNumber;
    data['bank_id'] = bankId;
    data['shareholder_unique_key'] = shareholderUniqueKey;
    data['bank_account_name'] = bankAccountName;
    data['pin_status'] = pinStatus;
    data['member_nickname'] = memberNickname;
    data['last_login_ip'] = lastLoginIp;
    data['member_avatar_url'] = memberAvatarUrl;
    data['member_qrcode_url'] = memberQrcodeUrl;
    data['auth_session'] = authSession;
    data['auth_expiry'] = authExpiry;
    data['member_type'] = memberType;
    data['admin_override'] = adminOverride;
    data['admin_override_expiry_datetime'] = adminOverrideExpiryDatetime;
    data['member_device_id'] = memberDeviceId;
    data['member_device'] = memberDevice;
    data['trace_history'] = traceHistory;
    data['shareholder_trace_history'] = shareholderTraceHistory;
    data['json_trace_history'] = jsonTraceHistory;
    data['member_qrcode_url_new'] = memberQrcodeUrlNew;
    data['avatar_last_update'] = avatarLastUpdate;
    data['json_shareholder_trace_history'] = jsonShareholderTraceHistory;
    data['fcm_token'] = fcmToken;
    data['member_language'] = memberLanguage;
    data['member_permission'] = memberPermission;
    data['member_referral_url'] = memberReferralUrl;
    data['member_directline'] = memberDirectline;
    data['member_login_token'] = memberLoginToken;
    data['member_country'] = memberCountry;
    data['vip_level_id'] = vipLevelId;
    data['member_country_origin'] = memberCountryOrigin;
    data['wallet_pin'] = walletPin;
    data['wallet_pin_reset_otp'] = walletPinResetOtp;
    data['is_transferring'] = isTransferring;
    data['member_topup_bank_id'] = memberTopupBankId;
    data['vip_last_update'] = vipLastUpdate;
    data['first_time_login'] = firstTimeLogin;
    data['walletBalance'] = walletBalance;
    data['coinBalance'] = coinBalance;
    data['interestBalance'] = interestBalance;
    data['country_id'] = countryId;
    data['country_name'] = countryName;
    data['country_code'] = countryCode;
    data['country_url'] = countryUrl;
    data['vip_max_withdraw_count'] = vipMaxWithdrawCount;
    data['vip_max_withdraw_amount'] = vipMaxWithdrawAmount;
    data['type'] = type;
    data['refMemberName'] = refMemberName;
    return data;
  }
}

class UserSessionModelResponse {
/*
{
  "user": {
    "id": "21",
    "member_unique_key": "CvrKJgMi16n3crLQ7CRprRKYihf9epbnp29DOcd3tW4FMyNpHYUQX6V7DERpzUY4DDcz8O9pOaR4PxogOGkysdPSNPxJB2gpABtfTkloRsMKxfY8Txklj0OCtHnOUKV0kaBmNBaZNsW3eOtUNelSM3rQ6zOLoxcsgAAaqRskdqygk5lIBRrsVbuBRcHpMIMTAD8aUeNW",
    "password": "68ea8013e0b1da0f9e01f6831a5fcf9a",
    "salt": "5sUTZHtm3AAlX/c4WL5DJzU6IG0kKnFENiWTicLKV3tcLG.5EOj9WQ==",
    "member_username": "Techtest",
    "member_level": "2",
    "ref_upline": "2",
    "member_main_id": "2",
    "member_phone_country": "+60",
    "member_phone": "103600016",
    "member_phone_otp": null,
    "member_phone_otp_salt": null,
    "member_phone_otp_status": "true",
    "last_login": "2022-11-18 21:41:04",
    "user_email": null,
    "registration_token": null,
    "account_status": "active",
    "account_status_remarks": null,
    "created_datetime": "2021-04-30 19:56:17",
    "password_otp": null,
    "password_otp_salt": null,
    "password_expiry": "2022-01-21 02:30:29",
    "bank_account_number": "2",
    "bank_id": "1",
    "shareholder_unique_key": "aHxbKIEsjLXK6jfsr3KNEuxFMuZkTpy9BMNzxyKOLwbVUuDV7DJLX7W9IY2eI6C1Abpw5YJPXiftI4I0DIj7MBUsTdtnKHVjEqdoRDtkSpEik4XdF1ZB1bapwMZINSmzaMH3EFAbUQuxWyto7sXPhp8IKcSpUE80kY2mYMnuuk1bjPnM5ovUfM6y0Ay3YozzDxRXNANJ",
    "bank_account_name": "Affin Bank",
    "pin_status": "true",
    "member_nickname": null,
    "last_login_ip": "162.158.170.141",
    "member_avatar_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/avatar/10.jpg",
    "member_qrcode_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/consumer/avatar/1675683361.png",
    "auth_session": "5fWJhYaSg2qnurPvXM1Y6pr5NOdCvfifsq0eDAdBcR8vUZuZ0eVYGEgulw3JvB2L6xR4FJIsiKAdfD9gvOE6UWJN6xPKufpvO0RmoYKs0hUr6y6C8cGIYS11b9qQOW95GVtQPSULDFyWsQP1yC6M7kLfZWhT8zfr0trQQgfnH0EAKsM3VEDdc6mMPL0BgWQmqEPRvMFM",
    "auth_expiry": "2022-11-19 21:41:04",
    "member_type": "normal",
    "admin_override": "false",
    "admin_override_expiry_datetime": null,
    "member_device_id": "58c549bc790a5ed4",
    "member_device": "android",
    "trace_history": "21-",
    "shareholder_trace_history": "1-",
    "json_trace_history": "[\"21\", \"\"]",
    "member_qrcode_url_new": null,
    "avatar_last_update": "2021-06-16 22:48:09",
    "json_shareholder_trace_history": "[\"1\", \"\"]",
    "fcm_token": "",
    "member_language": "en",
    "member_permission": null,
    "member_referral_url": null,
    "member_directline": "0",
    "member_login_token": null,
    "member_country": "2",
    "vip_level_id": "0",
    "member_country_origin": "1",
    "wallet_pin": "000000",
    "wallet_pin_reset_otp": null,
    "is_transferring": "0",
    "member_topup_bank_id": null,
    "vip_last_update": null,
    "first_time_login": "true",
    "walletBalance": "0.00",
    "coinBalance": "24.00",
    "interestBalance": "0.00",
    "country_id": "2",
    "country_name": "Thailand",
    "country_code": "THB",
    "country_url": "https://suncity.s3.ap-southeast-1.amazonaws.com/country/THB-flag.png",
    "vip_max_withdraw_count": "3",
    "vip_max_withdraw_amount": "200000.00",
    "type": "member",
    "refMemberName": "testtest"
  },
  "authSession": "pbMdLR32xSNKQdDaFq0iTuJuQWizRGmndwDkpGscnJC5VTFOpMluufsBg2X8wlUbV4ExXPuHgIRGVV5zQBRpbNjj9xRGDt7GST9Jzyed8B760z5WMSI64w58LbuglTxGTft4lBKTK62FQ836cnMkpFDNzHeRr49rOTP1FOYei5PxtqLOWcV93KIrJgrnOC8JHZ6JxjIn",
  "refLink": "https%3A%2F%2Fmember.luckytown.online%2FDownload%2Fapp%3Fref%3DTechtest",
  "authToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2Njg4NTUzNjUsImlzcyI6IiIsImV4cCI6MTY2ODk0MTc2NSwidXNlclRva2VuIjoiQ3ZyS0pnTWkxNm4zY3JMUTdDUnByUktZaWhmOWVwYm5wMjlET2NkM3RXNEZNeU5wSFlVUVg2VjdERVJwelVZNEREY3o4TzlwT2FSNFB4b2dPR2t5c2RQU05QeEpCMmdwQUJ0ZlRrbG9Sc01LeGZZOFR4a2xqME9DdEhuT1VLVjBrYUJtTkJhWk5zVzNlT3RVTmVsU00zclE2ek9Mb3hjc2dBQWFxUnNrZHF5Z2s1bElCUnJzVmJ1QlJjSHBNSU1UQUQ4YVVlTlciLCJ1c2VyVHlwZSI6Im1lbWJlciIsInVzZXJBdXRoIjoicGJNZExSMzJ4U05LUWREYUZxMGlUdUp1UVdpelJHbW5kd0RrcEdzY25KQzVWVEZPcE1sdXVmc0JnMlg4d2xVYlY0RXhYUHVIZ0lSR1ZWNXpRQlJwYk5qajl4UkdEdDdHU1Q5Snp5ZWQ4Qjc2MHo1V01TSTY0dzU4TGJ1Z2xUeEdUZnQ0bEJLVEs2MkZRODM2Y25Na3BGRE56SGVScjQ5ck9UUDFGT1llaTVQeHRxTE9XY1Y5M0tJckpncm5PQzhKSFo2SnhqSW4ifQ.UomhHb3ntWCZX7zxZSIOZvxryopfsZtRSmsM6J0T1UQ"
} 
*/

  UserSessionModelResponseUser? user;
  String? authSession;
  String? refLink;
  String? authToken;

  UserSessionModelResponse({
    this.user,
    this.authSession,
    this.refLink,
    this.authToken,
  });
  UserSessionModelResponse.fromJson(Map<String, dynamic> json) {
    user = (json['user'] != null)
        ? UserSessionModelResponseUser.fromJson(json['user'])
        : null;
    authSession = json['authSession']?.toString();
    refLink = json['refLink']?.toString();
    authToken = json['authToken']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['authSession'] = authSession;
    data['refLink'] = refLink;
    data['authToken'] = authToken;
    return data;
  }
}

class UserSessionModel {
/*
{
  "msg": "User Login Success",
  "response": {
    "user": {
      "id": "21",
      "member_unique_key": "CvrKJgMi16n3crLQ7CRprRKYihf9epbnp29DOcd3tW4FMyNpHYUQX6V7DERpzUY4DDcz8O9pOaR4PxogOGkysdPSNPxJB2gpABtfTkloRsMKxfY8Txklj0OCtHnOUKV0kaBmNBaZNsW3eOtUNelSM3rQ6zOLoxcsgAAaqRskdqygk5lIBRrsVbuBRcHpMIMTAD8aUeNW",
      "password": "68ea8013e0b1da0f9e01f6831a5fcf9a",
      "salt": "5sUTZHtm3AAlX/c4WL5DJzU6IG0kKnFENiWTicLKV3tcLG.5EOj9WQ==",
      "member_username": "Techtest",
      "member_level": "2",
      "ref_upline": "2",
      "member_main_id": "2",
      "member_phone_country": "+60",
      "member_phone": "103600016",
      "member_phone_otp": null,
      "member_phone_otp_salt": null,
      "member_phone_otp_status": "true",
      "last_login": "2022-11-18 21:41:04",
      "user_email": null,
      "registration_token": null,
      "account_status": "active",
      "account_status_remarks": null,
      "created_datetime": "2021-04-30 19:56:17",
      "password_otp": null,
      "password_otp_salt": null,
      "password_expiry": "2022-01-21 02:30:29",
      "bank_account_number": "2",
      "bank_id": "1",
      "shareholder_unique_key": "aHxbKIEsjLXK6jfsr3KNEuxFMuZkTpy9BMNzxyKOLwbVUuDV7DJLX7W9IY2eI6C1Abpw5YJPXiftI4I0DIj7MBUsTdtnKHVjEqdoRDtkSpEik4XdF1ZB1bapwMZINSmzaMH3EFAbUQuxWyto7sXPhp8IKcSpUE80kY2mYMnuuk1bjPnM5ovUfM6y0Ay3YozzDxRXNANJ",
      "bank_account_name": "Affin Bank",
      "pin_status": "true",
      "member_nickname": null,
      "last_login_ip": "162.158.170.141",
      "member_avatar_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/avatar/10.jpg",
      "member_qrcode_url": "https://suncity.s3-ap-southeast-1.amazonaws.com/consumer/avatar/1675683361.png",
      "auth_session": "5fWJhYaSg2qnurPvXM1Y6pr5NOdCvfifsq0eDAdBcR8vUZuZ0eVYGEgulw3JvB2L6xR4FJIsiKAdfD9gvOE6UWJN6xPKufpvO0RmoYKs0hUr6y6C8cGIYS11b9qQOW95GVtQPSULDFyWsQP1yC6M7kLfZWhT8zfr0trQQgfnH0EAKsM3VEDdc6mMPL0BgWQmqEPRvMFM",
      "auth_expiry": "2022-11-19 21:41:04",
      "member_type": "normal",
      "admin_override": "false",
      "admin_override_expiry_datetime": null,
      "member_device_id": "58c549bc790a5ed4",
      "member_device": "android",
      "trace_history": "21-",
      "shareholder_trace_history": "1-",
      "json_trace_history": "[\"21\", \"\"]",
      "member_qrcode_url_new": null,
      "avatar_last_update": "2021-06-16 22:48:09",
      "json_shareholder_trace_history": "[\"1\", \"\"]",
      "fcm_token": "",
      "member_language": "en",
      "member_permission": null,
      "member_referral_url": null,
      "member_directline": "0",
      "member_login_token": null,
      "member_country": "2",
      "vip_level_id": "0",
      "member_country_origin": "1",
      "wallet_pin": "000000",
      "wallet_pin_reset_otp": null,
      "is_transferring": "0",
      "member_topup_bank_id": null,
      "vip_last_update": null,
      "first_time_login": "true",
      "walletBalance": "0.00",
      "coinBalance": "24.00",
      "interestBalance": "0.00",
      "country_id": "2",
      "country_name": "Thailand",
      "country_code": "THB",
      "country_url": "https://suncity.s3.ap-southeast-1.amazonaws.com/country/THB-flag.png",
      "vip_max_withdraw_count": "3",
      "vip_max_withdraw_amount": "200000.00",
      "type": "member",
      "refMemberName": "testtest"
    },
    "authSession": "pbMdLR32xSNKQdDaFq0iTuJuQWizRGmndwDkpGscnJC5VTFOpMluufsBg2X8wlUbV4ExXPuHgIRGVV5zQBRpbNjj9xRGDt7GST9Jzyed8B760z5WMSI64w58LbuglTxGTft4lBKTK62FQ836cnMkpFDNzHeRr49rOTP1FOYei5PxtqLOWcV93KIrJgrnOC8JHZ6JxjIn",
    "refLink": "https%3A%2F%2Fmember.luckytown.online%2FDownload%2Fapp%3Fref%3DTechtest",
    "authToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2Njg4NTUzNjUsImlzcyI6IiIsImV4cCI6MTY2ODk0MTc2NSwidXNlclRva2VuIjoiQ3ZyS0pnTWkxNm4zY3JMUTdDUnByUktZaWhmOWVwYm5wMjlET2NkM3RXNEZNeU5wSFlVUVg2VjdERVJwelVZNEREY3o4TzlwT2FSNFB4b2dPR2t5c2RQU05QeEpCMmdwQUJ0ZlRrbG9Sc01LeGZZOFR4a2xqME9DdEhuT1VLVjBrYUJtTkJhWk5zVzNlT3RVTmVsU00zclE2ek9Mb3hjc2dBQWFxUnNrZHF5Z2s1bElCUnJzVmJ1QlJjSHBNSU1UQUQ4YVVlTlciLCJ1c2VyVHlwZSI6Im1lbWJlciIsInVzZXJBdXRoIjoicGJNZExSMzJ4U05LUWREYUZxMGlUdUp1UVdpelJHbW5kd0RrcEdzY25KQzVWVEZPcE1sdXVmc0JnMlg4d2xVYlY0RXhYUHVIZ0lSR1ZWNXpRQlJwYk5qajl4UkdEdDdHU1Q5Snp5ZWQ4Qjc2MHo1V01TSTY0dzU4TGJ1Z2xUeEdUZnQ0bEJLVEs2MkZRODM2Y25Na3BGRE56SGVScjQ5ck9UUDFGT1llaTVQeHRxTE9XY1Y5M0tJckpncm5PQzhKSFo2SnhqSW4ifQ.UomhHb3ntWCZX7zxZSIOZvxryopfsZtRSmsM6J0T1UQ"
  }
} 
*/

  String? msg;
  UserSessionModelResponse? response;

  UserSessionModel({
    this.msg,
    this.response,
  });
  UserSessionModel.fromJson(Map<String, dynamic> json) {
    msg = json['msg']?.toString();
    response = (json['response'] != null)
        ? UserSessionModelResponse.fromJson(json['response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['msg'] = msg;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
