///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BankModelResponseAccounts {
/*
{
  "id": "89",
  "member_id": "21",
  "bank_id": "29",
  "account_number": "123432234",
  "account_name": "John Tuso",
  "created_at": "2022-11-26 19:55:18",
  "updated_at": "2022-11-26 19:55:18",
  "bank_name": "Thai bank",
  "bank_country": "2",
  "bank_type": "cash",
  "bank_icon_url": "https://xxyyzz112233.s3-ap-southeast-1.amazonaws.com/topupBank/1748802814.jpeg"
} 
*/

  String? id;
  String? memberId;
  String? bankId;
  String? accountNumber;
  String? accountName;
  String? createdAt;
  String? updatedAt;
  String? bankName;
  String? bankCountry;
  String? bankType;
  String? bankIconUrl;

  BankModelResponseAccounts({
    this.id,
    this.memberId,
    this.bankId,
    this.accountNumber,
    this.accountName,
    this.createdAt,
    this.updatedAt,
    this.bankName,
    this.bankCountry,
    this.bankType,
    this.bankIconUrl,
  });
  BankModelResponseAccounts.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    memberId = json['member_id']?.toString();
    bankId = json['bank_id']?.toString();
    accountNumber = json['account_number']?.toString();
    accountName = json['account_name']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    bankName = json['bank_name']?.toString();
    bankCountry = json['bank_country']?.toString();
    bankType = json['bank_type']?.toString();
    bankIconUrl = json['bank_icon_url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['member_id'] = memberId;
    data['bank_id'] = bankId;
    data['account_number'] = accountNumber;
    data['account_name'] = accountName;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['bank_name'] = bankName;
    data['bank_country'] = bankCountry;
    data['bank_type'] = bankType;
    data['bank_icon_url'] = bankIconUrl;
    return data;
  }
}

class BankModelResponse {
/*
{
  "accounts": [
    {
      "id": "89",
      "member_id": "21",
      "bank_id": "29",
      "account_number": "123432234",
      "account_name": "John Tuso",
      "created_at": "2022-11-26 19:55:18",
      "updated_at": "2022-11-26 19:55:18",
      "bank_name": "Thai bank",
      "bank_country": "2",
      "bank_type": "cash",
      "bank_icon_url": "https://xxyyzz112233.s3-ap-southeast-1.amazonaws.com/topupBank/1748802814.jpeg"
    }
  ]
} 
*/

  List<BankModelResponseAccounts?>? accounts;

  BankModelResponse({
    this.accounts,
  });
  BankModelResponse.fromJson(Map<String, dynamic> json) {
    if (json['accounts'] != null) {
      final v = json['accounts'];
      final arr0 = <BankModelResponseAccounts>[];
      v.forEach((v) {
        arr0.add(BankModelResponseAccounts.fromJson(v));
      });
      accounts = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (accounts != null) {
      final v = accounts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['accounts'] = arr0;
    }
    return data;
  }
}

class BankModel {
/*
{
  "msg": "Member bank accounts retrieved successfully.",
  "response": {
    "accounts": [
      {
        "id": "89",
        "member_id": "21",
        "bank_id": "29",
        "account_number": "123432234",
        "account_name": "John Tuso",
        "created_at": "2022-11-26 19:55:18",
        "updated_at": "2022-11-26 19:55:18",
        "bank_name": "Thai bank",
        "bank_country": "2",
        "bank_type": "cash",
        "bank_icon_url": "https://xxyyzz112233.s3-ap-southeast-1.amazonaws.com/topupBank/1748802814.jpeg"
      }
    ]
  }
} 
*/

  String? msg;
  BankModelResponse? response;

  BankModel({
    this.msg,
    this.response,
  });
  BankModel.fromJson(Map<String, dynamic> json) {
    msg = json['msg']?.toString();
    response = (json['response'] != null)
        ? BankModelResponse.fromJson(json['response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['msg'] = msg;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
