///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ExistingBankModelResponseBankList {
/*
{
  "bank_id": "29",
  "bank_name": "Thai bank",
  "bank_country": "2",
  "bank_type": "cash",
  "bank_icon_url": "https://xxyyzz112233.s3-ap-southeast-1.amazonaws.com/topupBank/1748802814.jpeg"
} 
*/

  String? bankId;
  String? bankName;
  String? bankCountry;
  String? bankType;
  String? bankIconUrl;

  ExistingBankModelResponseBankList({
    this.bankId,
    this.bankName,
    this.bankCountry,
    this.bankType,
    this.bankIconUrl,
  });
  ExistingBankModelResponseBankList.fromJson(Map<String, dynamic> json) {
    bankId = json['bank_id']?.toString();
    bankName = json['bank_name']?.toString();
    bankCountry = json['bank_country']?.toString();
    bankType = json['bank_type']?.toString();
    bankIconUrl = json['bank_icon_url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bank_id'] = bankId;
    data['bank_name'] = bankName;
    data['bank_country'] = bankCountry;
    data['bank_type'] = bankType;
    data['bank_icon_url'] = bankIconUrl;
    return data;
  }
}

class ExistingBankModelResponse {
/*
{
  "bankList": [
    {
      "bank_id": "29",
      "bank_name": "Thai bank",
      "bank_country": "2",
      "bank_type": "cash",
      "bank_icon_url": "https://xxyyzz112233.s3-ap-southeast-1.amazonaws.com/topupBank/1748802814.jpeg"
    }
  ]
} 
*/

  List<ExistingBankModelResponseBankList?>? bankList;

  ExistingBankModelResponse({
    this.bankList,
  });
  ExistingBankModelResponse.fromJson(Map<String, dynamic> json) {
    if (json['bankList'] != null) {
      final v = json['bankList'];
      final arr0 = <ExistingBankModelResponseBankList>[];
      v.forEach((v) {
        arr0.add(ExistingBankModelResponseBankList.fromJson(v));
      });
      bankList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (bankList != null) {
      final v = bankList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['bankList'] = arr0;
    }
    return data;
  }
}

class ExistingBankModel {
/*
{
  "msg": "Get Bank List Success.",
  "response": {
    "bankList": [
      {
        "bank_id": "29",
        "bank_name": "Thai bank",
        "bank_country": "2",
        "bank_type": "cash",
        "bank_icon_url": "https://xxyyzz112233.s3-ap-southeast-1.amazonaws.com/topupBank/1748802814.jpeg"
      }
    ]
  }
} 
*/

  String? msg;
  ExistingBankModelResponse? response;

  ExistingBankModel({
    this.msg,
    this.response,
  });
  ExistingBankModel.fromJson(Map<String, dynamic> json) {
    msg = json['msg']?.toString();
    response = (json['response'] != null)
        ? ExistingBankModelResponse.fromJson(json['response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['msg'] = msg;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
