///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ExistingBankModelResponseBankList {
/*
{
  "bank_id": "1",
  "bank_name": "Affin Bank",
  "bank_country": "1",
  "bank_type": "cash",
  "bank_icon_url": "https://suncity.s3.ap-southeast-1.amazonaws.com/bank/affin.png"
} 
*/

  String? bank_id;
  String? bank_name;
  String? bank_country;
  String? bank_type;
  String? bank_icon_url;

  ExistingBankModelResponseBankList({
    this.bank_id,
    this.bank_name,
    this.bank_country,
    this.bank_type,
    this.bank_icon_url,
  });
  ExistingBankModelResponseBankList.fromJson(Map<String, dynamic> json) {
    bank_id = json['bank_id']?.toString();
    bank_name = json['bank_name']?.toString();
    bank_country = json['bank_country']?.toString();
    bank_type = json['bank_type']?.toString();
    bank_icon_url = json['bank_icon_url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bank_id'] = bank_id;
    data['bank_name'] = bank_name;
    data['bank_country'] = bank_country;
    data['bank_type'] = bank_type;
    data['bank_icon_url'] = bank_icon_url;
    return data;
  }
}

class ExistingBankModelResponse {
/*
{
  "bankList": [
    {
      "bank_id": "1",
      "bank_name": "Affin Bank",
      "bank_country": "1",
      "bank_type": "cash",
      "bank_icon_url": "https://suncity.s3.ap-southeast-1.amazonaws.com/bank/affin.png"
    }
  ]
} 
*/

  List<ExistingBankModelResponseBankList?>? bankList;

  ExistingBankModelResponse({
    this.bankList,
  });
  ExistingBankModelResponse.fromJson(Map<String, dynamic> json) {
    if (json['bankList'] != null) {
      final v = json['bankList'];
      final arr0 = <ExistingBankModelResponseBankList>[];
      v.forEach((v) {
        arr0.add(ExistingBankModelResponseBankList.fromJson(v));
      });
      bankList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (bankList != null) {
      final v = bankList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['bankList'] = arr0;
    }
    return data;
  }
}

class ExistingBankModel {
/*
{
  "msg": "Get Bank List Success.",
  "response": {
    "bankList": [
      {
        "bank_id": "1",
        "bank_name": "Affin Bank",
        "bank_country": "1",
        "bank_type": "cash",
        "bank_icon_url": "https://suncity.s3.ap-southeast-1.amazonaws.com/bank/affin.png"
      }
    ]
  }
} 
*/

  String? msg;
  ExistingBankModelResponse? response;

  ExistingBankModel({
    this.msg,
    this.response,
  });
  ExistingBankModel.fromJson(Map<String, dynamic> json) {
    msg = json['msg']?.toString();
    response = (json['response'] != null)
        ? ExistingBankModelResponse.fromJson(json['response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['msg'] = msg;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
