///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AllGameTransactionModelResponseTransactionsJsonClickDetailsJsonText {
/*
{
  "Transaction Number": "918KISS-437df1ab-2e45-4fa3-a0a2-1293f70ab1c9",
  "Type": "Bet",
  "Valid Bet": "0.0000",
  "Payout": "0.00",
  "Win/Loss": "0.00",
  "Remarks": "918KISS",
  "Date/Time": "2021-10-30 21:48:15"
} 
*/

  String? TransactionNumber;
  String? Type;
  String? ValidBet;
  String? Payout;
  String? WinLoss;
  String? Remarks;
  String? DateTime;

  AllGameTransactionModelResponseTransactionsJsonClickDetailsJsonText({
    this.TransactionNumber,
    this.Type,
    this.ValidBet,
    this.Payout,
    this.WinLoss,
    this.Remarks,
    this.DateTime,
  });
  AllGameTransactionModelResponseTransactionsJsonClickDetailsJsonText.fromJson(
      Map<String, dynamic> json) {
    TransactionNumber = json['Transaction Number']?.toString();
    Type = json['Type']?.toString();
    ValidBet = json['Valid Bet']?.toString();
    Payout = json['Payout']?.toString();
    WinLoss = json['Win/Loss']?.toString();
    Remarks = json['Remarks']?.toString();
    DateTime = json['Date/Time']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Transaction Number'] = TransactionNumber;
    data['Type'] = Type;
    data['Valid Bet'] = ValidBet;
    data['Payout'] = Payout;
    data['Win/Loss'] = WinLoss;
    data['Remarks'] = Remarks;
    data['Date/Time'] = DateTime;
    return data;
  }
}

class AllGameTransactionModelResponseTransactionsJsonClickDetails {
/*
{
  "jsonText": {
    "Transaction Number": "918KISS-437df1ab-2e45-4fa3-a0a2-1293f70ab1c9",
    "Type": "Bet",
    "Valid Bet": "0.0000",
    "Payout": "0.00",
    "Win/Loss": "0.00",
    "Remarks": "918KISS",
    "Date/Time": "2021-10-30 21:48:15"
  },
  "detailClick": "true",
  "detailJson": null
} 
*/

  AllGameTransactionModelResponseTransactionsJsonClickDetailsJsonText? jsonText;
  String? detailClick;
  String? detailJson;

  AllGameTransactionModelResponseTransactionsJsonClickDetails({
    this.jsonText,
    this.detailClick,
    this.detailJson,
  });
  AllGameTransactionModelResponseTransactionsJsonClickDetails.fromJson(
      Map<String, dynamic> json) {
    jsonText = (json['jsonText'] != null)
        ? AllGameTransactionModelResponseTransactionsJsonClickDetailsJsonText
            .fromJson(json['jsonText'])
        : null;
    detailClick = json['detailClick']?.toString();
    detailJson = json['detailJson']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (jsonText != null) {
      data['jsonText'] = jsonText!.toJson();
    }
    data['detailClick'] = detailClick;
    data['detailJson'] = detailJson;
    return data;
  }
}

class AllGameTransactionModelResponseTransactions {
/*
{
  "transaction_id": "45929064",
  "game_transaction_valid_stake": "0.0000",
  "game_transaction_winloss": "0.00",
  "transaction_number": "918KISS-437df1ab-2e45-4fa3-a0a2-1293f70ab1c9",
  "transaction_remarks": "918KISS",
  "transaction_created_datetime": "2021-10-30 21:48:15",
  "product_image_url": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/918kiss.png",
  "game_transaction_stake": "0.0000",
  "transaction_amount": "0.0000",
  "game_transaction_payout": "0.00",
  "transaction_type": "bet",
  "game_transaction_product": "918KISS",
  "game_transaction_category": "EGAMES",
  "jsonClickDetails": {
    "jsonText": {
      "Transaction Number": "918KISS-437df1ab-2e45-4fa3-a0a2-1293f70ab1c9",
      "Type": "Bet",
      "Valid Bet": "0.0000",
      "Payout": "0.00",
      "Win/Loss": "0.00",
      "Remarks": "918KISS",
      "Date/Time": "2021-10-30 21:48:15"
    },
    "detailClick": "true",
    "detailJson": null
  }
} 
*/

  String? transaction_id;
  String? game_transaction_valid_stake;
  String? game_transaction_winloss;
  String? transaction_number;
  String? transaction_remarks;
  String? transaction_created_datetime;
  String? product_image_url;
  String? game_transaction_stake;
  String? transaction_amount;
  String? game_transaction_payout;
  String? transaction_type;
  String? game_transaction_product;
  String? game_transaction_category;
  AllGameTransactionModelResponseTransactionsJsonClickDetails? jsonClickDetails;

  AllGameTransactionModelResponseTransactions({
    this.transaction_id,
    this.game_transaction_valid_stake,
    this.game_transaction_winloss,
    this.transaction_number,
    this.transaction_remarks,
    this.transaction_created_datetime,
    this.product_image_url,
    this.game_transaction_stake,
    this.transaction_amount,
    this.game_transaction_payout,
    this.transaction_type,
    this.game_transaction_product,
    this.game_transaction_category,
    this.jsonClickDetails,
  });
  AllGameTransactionModelResponseTransactions.fromJson(
      Map<String, dynamic> json) {
    transaction_id = json['transaction_id']?.toString();
    game_transaction_valid_stake =
        json['game_transaction_valid_stake']?.toString();
    game_transaction_winloss = json['game_transaction_winloss']?.toString();
    transaction_number = json['transaction_number']?.toString();
    transaction_remarks = json['transaction_remarks']?.toString();
    transaction_created_datetime =
        json['transaction_created_datetime']?.toString();
    product_image_url = json['product_image_url']?.toString();
    game_transaction_stake = json['game_transaction_stake']?.toString();
    transaction_amount = json['transaction_amount']?.toString();
    game_transaction_payout = json['game_transaction_payout']?.toString();
    transaction_type = json['transaction_type']?.toString();
    game_transaction_product = json['game_transaction_product']?.toString();
    game_transaction_category = json['game_transaction_category']?.toString();
    jsonClickDetails = (json['jsonClickDetails'] != null)
        ? AllGameTransactionModelResponseTransactionsJsonClickDetails.fromJson(
            json['jsonClickDetails'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['transaction_id'] = transaction_id;
    data['game_transaction_valid_stake'] = game_transaction_valid_stake;
    data['game_transaction_winloss'] = game_transaction_winloss;
    data['transaction_number'] = transaction_number;
    data['transaction_remarks'] = transaction_remarks;
    data['transaction_created_datetime'] = transaction_created_datetime;
    data['product_image_url'] = product_image_url;
    data['game_transaction_stake'] = game_transaction_stake;
    data['transaction_amount'] = transaction_amount;
    data['game_transaction_payout'] = game_transaction_payout;
    data['transaction_type'] = transaction_type;
    data['game_transaction_product'] = game_transaction_product;
    data['game_transaction_category'] = game_transaction_category;
    if (jsonClickDetails != null) {
      data['jsonClickDetails'] = jsonClickDetails!.toJson();
    }
    return data;
  }
}

class AllGameTransactionModelResponse {
/*
{
  "transactions": [
    {
      "transaction_id": "45929064",
      "game_transaction_valid_stake": "0.0000",
      "game_transaction_winloss": "0.00",
      "transaction_number": "918KISS-437df1ab-2e45-4fa3-a0a2-1293f70ab1c9",
      "transaction_remarks": "918KISS",
      "transaction_created_datetime": "2021-10-30 21:48:15",
      "product_image_url": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/918kiss.png",
      "game_transaction_stake": "0.0000",
      "transaction_amount": "0.0000",
      "game_transaction_payout": "0.00",
      "transaction_type": "bet",
      "game_transaction_product": "918KISS",
      "game_transaction_category": "EGAMES",
      "jsonClickDetails": {
        "jsonText": {
          "Transaction Number": "918KISS-437df1ab-2e45-4fa3-a0a2-1293f70ab1c9",
          "Type": "Bet",
          "Valid Bet": "0.0000",
          "Payout": "0.00",
          "Win/Loss": "0.00",
          "Remarks": "918KISS",
          "Date/Time": "2021-10-30 21:48:15"
        },
        "detailClick": "true",
        "detailJson": null
      }
    }
  ],
  "fromDate": "2021-07-25",
  "toDate": "2022-07-31"
} 
*/

  List<AllGameTransactionModelResponseTransactions?>? transactions;
  String? fromDate;
  String? toDate;

  AllGameTransactionModelResponse({
    this.transactions,
    this.fromDate,
    this.toDate,
  });
  AllGameTransactionModelResponse.fromJson(Map<String, dynamic> json) {
    if (json['transactions'] != null) {
      final v = json['transactions'];
      final arr0 = <AllGameTransactionModelResponseTransactions>[];
      v.forEach((v) {
        arr0.add(AllGameTransactionModelResponseTransactions.fromJson(v));
      });
      transactions = arr0;
    }
    fromDate = json['fromDate']?.toString();
    toDate = json['toDate']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (transactions != null) {
      final v = transactions;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['transactions'] = arr0;
    }
    data['fromDate'] = fromDate;
    data['toDate'] = toDate;
    return data;
  }
}

class AllGameTransactionModel {
/*
{
  "msg": "Get All Game Transactions Success.",
  "response": {
    "transactions": [
      {
        "transaction_id": "45929064",
        "game_transaction_valid_stake": "0.0000",
        "game_transaction_winloss": "0.00",
        "transaction_number": "918KISS-437df1ab-2e45-4fa3-a0a2-1293f70ab1c9",
        "transaction_remarks": "918KISS",
        "transaction_created_datetime": "2021-10-30 21:48:15",
        "product_image_url": "https://xxyyzz112233.s3.ap-southeast-1.amazonaws.com/product/918kiss.png",
        "game_transaction_stake": "0.0000",
        "transaction_amount": "0.0000",
        "game_transaction_payout": "0.00",
        "transaction_type": "bet",
        "game_transaction_product": "918KISS",
        "game_transaction_category": "EGAMES",
        "jsonClickDetails": {
          "jsonText": {
            "Transaction Number": "918KISS-437df1ab-2e45-4fa3-a0a2-1293f70ab1c9",
            "Type": "Bet",
            "Valid Bet": "0.0000",
            "Payout": "0.00",
            "Win/Loss": "0.00",
            "Remarks": "918KISS",
            "Date/Time": "2021-10-30 21:48:15"
          },
          "detailClick": "true",
          "detailJson": null
        }
      }
    ],
    "fromDate": "2021-07-25",
    "toDate": "2022-07-31"
  }
} 
*/

  String? msg;
  AllGameTransactionModelResponse? response;

  AllGameTransactionModel({
    this.msg,
    this.response,
  });
  AllGameTransactionModel.fromJson(Map<String, dynamic> json) {
    msg = json['msg']?.toString();
    response = (json['response'] != null)
        ? AllGameTransactionModelResponse.fromJson(json['response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['msg'] = msg;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
